/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Action
   * Actions show the results and progress of asynchronous requests to the API.
   */
case class Action(
  /* Command executed in the Action. */
  @named("command") command: String,
  /* Error message for the Action if an error occurred, otherwise null. */
  @named("error") error: Error,
  /* Point in time when the Action was finished (in ISO-8601 format). Only set if the Action is finished otherwise null. */
  @named("finished") finished: String,
  /* ID of the Action. */
  @named("id") id: Long,
  /* Progress of the Action in percent. */
  @named("progress") progress: Int,
  /* Resources the Action relates to. */
  @named("resources") resources: Seq[Resource],
  /* Point in time when the Action was started (in ISO-8601 format). */
  @named("started") started: String,
  /* Status of the Action. */
  @named("status") status: ActionEnums.Status
)

object ActionEnums:
  enum Status:
    case `error`
    case `running`
    case `success`

  object Status:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given statusCodec: JsonValueCodec[Status] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "error" => "error"
            case "running" => "running"
            case "success" => "success"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end ActionEnums
