/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Request for POST
  * https://api.hetzner.cloud/v1/zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/add_records
  */
case class AddRecordsToRrsetRequest(
    /* Records to add to the RRSet.  Must not be empty and must only contain distinct record values.  */
    @named("records") records: Seq[ResourceRecord],
    /* Time To Live (TTL) of the RRSet.  If not set, the Zone's Default TTL is used. If set, and the RRSet being updated already has a TTL, the values must be the same.  */
    @named("ttl") ttl: Option[Int] = scala.None
)
