/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * AddToPlacementGroupRequest
   * Request for POST https://api.hetzner.cloud/v1/servers/{id}/actions/add_to_placement_group
   */
case class AddServerToPlacementGroupRequest(
  /* ID of Placement Group the Server should be added to. */
  @named("placement_group") placementGroup: Long
)

