/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * CPU architecture compatible with the Image.  | CPU architecture compatible with the ISO.  Null indicates no restriction on the architecture (wildcard).  | CPU architecture of the Server Type. 
   */

enum Architecture:
  case `arm`
  case `x86`

object Architecture:
  import com.github.plokhotnyuk.jsoniter_scala.macros.*
  import com.github.plokhotnyuk.jsoniter_scala.core.*
  given architectureCodec: JsonValueCodec[Architecture] = JsonCodecMaker.make {
    CodecMakerConfig
      .withAdtLeafClassNameMapper { x =>
        JsonCodecMaker.simpleClassName(x) match
          case "arm" => "arm"
          case "x86" => "x86"
      }
      .withDiscriminatorFieldName(scala.None)
  }
end Architecture

