/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PrimaryIPActionsAssignRequest Request for POST
  * https://api.hetzner.cloud/v1/primary_ips/{id}/actions/assign
  */
case class AssignPrimaryIpToResourceRequest(
    /* ID of a resource of type `assignee_type`. */
    @named("assignee_id") assigneeId: Long,
    /* Type of resource assigning the Primary IP to. */
    @named(
      "assignee_type"
    ) assigneeType: AssignPrimaryIpToResourceRequestEnums.AssigneeType
)

object AssignPrimaryIpToResourceRequestEnums:
  enum AssigneeType:
    case `server`

  object AssigneeType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given assigneeTypeCodec: JsonValueCodec[AssigneeType] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "server" => "server"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end AssignPrimaryIpToResourceRequestEnums
