/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Current status of a type `managed` Certificate, always *null* for type `uploaded` Certificates.
   */
case class CertificateStatus(
  @named("error") error: Option[CertificateStatusError] = scala.None,
  /* Status of the issuance process of the Certificate. */
  @named("issuance") issuance: Option[CertificateStatusEnums.Issuance] = scala.None,
  /* Status of the renewal process of the Certificate. */
  @named("renewal") renewal: Option[CertificateStatusEnums.Renewal] = scala.None
)

object CertificateStatusEnums:
  enum Issuance:
    case `completed`
    case `failed`
    case `pending`

  object Issuance:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given issuanceCodec: JsonValueCodec[Issuance] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "completed" => "completed"
            case "failed" => "failed"
            case "pending" => "pending"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum Renewal:
    case `failed`
    case `pending`
    case `scheduled`
    case `unavailable`

  object Renewal:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given renewalCodec: JsonValueCodec[Renewal] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "failed" => "failed"
            case "pending" => "pending"
            case "scheduled" => "scheduled"
            case "unavailable" => "unavailable"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end CertificateStatusEnums
