/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ChangeIPRangeRequest Request for POST
  * https://api.hetzner.cloud/v1/networks/{id}/actions/change_ip_range
  */
case class ChangeIpRangeOfNetworkRequest(
    /* IP range of the Network.  Uses CIDR notation.  Must span all included subnets. Must be one of the private IPv4 ranges of RFC1918.  Minimum network size is /24. We highly recommend that you pick a larger Network with a /16 netmask.  */
    @named("ip_range") ipRange: String
)
