/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ChangeProtectionRequest Request for POST
  * https://api.hetzner.cloud/v1/networks/{id}/actions/change_protection
  */
case class ChangeNetworkProtectionRequest(
    /* Delete protection setting.  If true, prevents the Network from being deleted.  */
    @named("delete") delete: Option[Boolean] = scala.None
)
