/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ChangeLoadbalancerDnsPtrRequest Request for POST
  * https://api.hetzner.cloud/v1/load_balancers/{id}/actions/change_dns_ptr
  */
case class ChangeReverseDnsEntryForThisLoadBalancerRequest(
    /* Hostname to set as a reverse DNS PTR entry. */
    @named("dns_ptr") dnsPtr: String,
    /* Public IP address for which the reverse DNS entry should be set. */
    @named("ip") ip: String
)
