/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Request for POST https://api.hetzner.cloud/v1/servers/{id}/actions/change_alias_ips
   */
case class ChangeAliasIpsOfNetworkRequest(
  /* New alias IPs to set for this Server. */
  @named("alias_ips") aliasIps: Seq[String],
  /* ID of an existing Network already attached to the Server. */
  @named("network") network: Long
)

