/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * ChangeTypeRequest
   * Request for POST https://api.hetzner.cloud/v1/load_balancers/{id}/actions/change_type
   */
case class ChangeTypeOfLoadBalancerRequest(
  /* ID or name of Load Balancer type the Load Balancer should migrate to. */
  @named("load_balancer_type") loadBalancerType: String
)

