/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Request for POST https://api.hetzner.cloud/v1/servers/{id}/actions/change_type
   */
case class ChangeTypeOfServerRequest(
  /* ID or name of Server type the Server should migrate to. */
  @named("server_type") serverType: String,
  /* If false, do not upgrade the disk (this allows downgrading the Server type later). */
  @named("upgrade_disk") upgradeDisk: Boolean
)

