/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** NetworkCreateRequest Request for POST https://api.hetzner.cloud/v1/networks
  */
case class CreateNetworkRequest(
    /* IP range of the Network.  Uses CIDR notation.  Must span all included subnets. Must be one of the private IPv4 ranges of RFC1918.  Minimum network size is /24. We highly recommend that you pick a larger Network with a /16 netmask.  */
    @named("ip_range") ipRange: String,
    /* Name of the Network. */
    @named("name") name: String,
    /* Toggle to expose routes to the Networks vSwitch.  Indicates if the routes from this Network should be exposed to the vSwitch in this Network. Only takes effect if a [vSwitch is setup](https://docs.hetzner.com/cloud/networks/connect-dedi-vswitch) in this Network.  */
    @named("expose_routes_to_vswitch") exposeRoutesToVswitch: Option[Boolean] =
      scala.None,
    /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
    @named("labels") labels: Option[Map[String, String]] = scala.None,
    /* Array of routes set in this Network. */
    @named("routes") routes: Option[Seq[Route]] = scala.None,
    /* Array of subnets to allocate. */
    @named("subnets") subnets: Option[Seq[Subnet]] = scala.None
)
