/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Request for POST https://api.hetzner.com/v1/storage_boxes
   */
case class CreateStorageBoxRequest(
  @named("access_settings") accessSettings: Option[CreateStorageBoxRequestAccessSettings] = scala.None,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Option[Map[String, String]] = scala.None,
  /* ID or Name of Location. */
  @named("location") location: String,
  /* Name of the Storage Box.  */
  @named("name") name: String,
  /* Password of the Storage Box.  For more details, see the Storage Boxes password policy.  */
  @named("password") password: String,
  /* SSH public keys in OpenSSH format to inject into the Storage Box. */
  @named("ssh_keys") sshKeys: Option[Seq[String]] = scala.None,
  /* ID or Name of the Storage Box Type. */
  @named("storage_box_type") storageBoxType: String
)

