/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * CreateFirewallRequest
   * Request for POST https://api.hetzner.cloud/v1/firewalls
   */
case class CreateFirewallRequest(
  /* Name of the Firewall.  Limited to a maximum of 128 characters.  Must be unique per Project.  */
  @named("name") name: String,
  /* Resources to apply the Firewall to.  Resources added directly are taking precedence over those added via a Label Selector.  */
  @named("apply_to") applyTo: Option[Seq[FirewallResource]] = scala.None,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Option[Map[String, String]] = scala.None,
  /* Array of rules.  Rules are limited to 50 entries per Firewall and [500 effective rules](https://docs.hetzner.com/cloud/firewalls/overview#limits).  */
  @named("rules") rules: Option[Seq[Rule]] = scala.None
)

