/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * CreateFirewallResponse
   * Response to POST https://api.hetzner.cloud/v1/firewalls
   */
case class CreateFirewallResponse(
  @named("actions") actions: Option[Seq[Action]] = scala.None,
  @named("firewall") firewall: Option[Firewall] = scala.None
)

