/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** CreatePlacementGroupRequest Request for POST
  * https://api.hetzner.cloud/v1/placement_groups
  */
case class CreatePlacementgroupRequest(
    /* Name of the Placement Group. */
    @named("name") name: String,
    /* Define the Placement Group Type. */
    @named("type") `type`: CreatePlacementgroupRequestEnums.Type,
    /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
    @named("labels") labels: Option[Map[String, String]] = scala.None
)

object CreatePlacementgroupRequestEnums:
  enum Type:
    case `spread`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "spread" => "spread"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end CreatePlacementgroupRequestEnums
