/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Request for POST https://api.hetzner.cloud/v1/zones
   */
case class CreateZoneRequest(
  /* Mode of the Zone.  For more information, see Zone Modes.  */
  @named("mode") mode: CreateZoneRequestEnums.Mode,
  /* Name of the Zone.  All names with [well-known public suffixes](https://publicsuffix.org/) (e.g. `.de`, `.com`, `.co.uk`) are supported. Subdomains are not supported.  The name must be in lower case and must not end with a dot. [Internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) must be transcribed to [Punycode](https://wikipedia.org/wiki/Punycode) representation with ACE prefix, e.g. `xn--mnchen-3ya.de` (`münchen.de`).  */
  @named("name") name: String,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Option[Map[String, String]] = scala.None,
  /* Primary nameservers of the Zone.  Only applicable for Zones in secondary mode. Ignored for Zones in primary mode.  */
  @named("primary_nameservers") primaryNameservers: Option[Seq[Nameserver]] = scala.None,
  /* RRSets to be added to the Zone.  Only applicable for Zones in primary mode. Ignored for Zones in secondary mode.  */
  @named("rrsets") rrsets: Option[Seq[ResourceRecordSetToCreate]] = scala.None,
  /* Default Time To Live (TTL) of the Zone.  Must be in between 60s and 2147483647s.  This TTL is used for RRSets that do not explicitly define a TTL.  */
  @named("ttl") ttl: Option[Int] = scala.None,
  /* Zone file to import.  Only applicable for Zones in primary mode. Ignored for Zones in secondary mode.  If provided, `rrsets` must be empty.  See Zone file import for more details.  */
  @named("zonefile") zonefile: Option[String] = scala.None
)

object CreateZoneRequestEnums:
  enum Mode:
    case `primary`
    case `secondary`

  object Mode:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given modeCodec: JsonValueCodec[Mode] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "primary" => "primary"
            case "secondary" => "secondary"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end CreateZoneRequestEnums
