/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import hcloud.models.IpType.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * FloatingIPCreateRequest
   * Request for POST https://api.hetzner.cloud/v1/floating_ips
   */
case class CreateFloatingIpRequest(
  /* Description of the Resource. */
  @named("description") description: Option[String] = scala.None,
  /* Home Location for the Floating IP.  Either the ID or the name of the Location.  Only optional if no Server is provided. Routing is optimized for this Locations.  */
  @named("home_location") homeLocation: Option[String] = scala.None,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Option[Map[String, String]] = scala.None,
  /* Name of the Resource. Must be unique per Project. */
  @named("name") name: Option[String] = scala.None,
  /* Server the Floating IP is assigned to.  `null` if not assigned.  */
  @named("server") server: Option[Long] = scala.None,
  @named("type") `type`: IpType
)

object CreateFloatingIpRequestEnums:
end CreateFloatingIpRequestEnums
