/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Access settings of the Storage Box.
   */
case class CreateStorageBoxRequestAccessSettings(
  /* Whether access from outside the Hetzner network is allowed. */
  @named("reachable_externally") reachableExternally: Option[Boolean] = scala.None,
  /* Whether the Samba subsystem is enabled. */
  @named("samba_enabled") sambaEnabled: Option[Boolean] = scala.None,
  /* Whether the SSH subsystem is enabled. */
  @named("ssh_enabled") sshEnabled: Option[Boolean] = scala.None,
  /* Whether the WebDAV subsystem is enabled. */
  @named("webdav_enabled") webdavEnabled: Option[Boolean] = scala.None,
  /* Whether the ZFS snapshot folder is visible. */
  @named("zfs_enabled") zfsEnabled: Option[Boolean] = scala.None
)

