/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * CreateCertificateRequest
   * Request for POST https://api.hetzner.cloud/v1/certificates
   */
case class CreateCertificateRequest(
  /* Certificate and chain in PEM format, in order so that each record directly certifies the one preceding. Required for type `uploaded` Certificates. */
  @named("certificate") certificate: Option[String] = scala.None,
  /* Domains and subdomains that should be contained in the Certificate issued by *Let's Encrypt*. Required for type `managed` Certificates. */
  @named("domain_names") domainNames: Option[Seq[String]] = scala.None,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Option[Map[String, String]] = scala.None,
  /* Name of the Certificate. */
  @named("name") name: String,
  /* Certificate key in PEM format. Required for type `uploaded` Certificates. */
  @named("private_key") privateKey: Option[String] = scala.None,
  /* Choose between uploading a Certificate in PEM format or requesting a managed *Let's Encrypt* Certificate. */
  @named("type") `type`: Option[CreateCertificateRequestEnums.Type] = scala.None
)

object CreateCertificateRequestEnums:
  enum Type:
    case `managed`
    case `uploaded`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "managed" => "managed"
            case "uploaded" => "uploaded"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end CreateCertificateRequestEnums
