/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Request for POST https://api.hetzner.com/v1/storage_boxes/{id}/subaccounts
  */
case class CreateSubaccountRequest(
    /* Home directory of the Storage Box Subaccount.  The directory will be created if it doesn't exist yet.  */
    @named("home_directory") homeDirectory: String,
    /* Password of the Storage Box Subaccount.  For more details, see the Storage Boxes password policy.  */
    @named("password") password: String,
    @named("access_settings") accessSettings: Option[
      CreateSubaccountRequestAccessSettings
    ] = scala.None,
    /* A description of Storage Box Subaccount.  */
    @named("description") description: Option[String] = scala.None,
    /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
    @named("labels") labels: Option[Map[String, String]] = scala.None
)
