/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Public Network options.
   */
case class CreateServerRequestPublicNet(
  /* Attach an IPv4 on the public NIC. If false, no IPv4 address will be attached. */
  @named("enable_ipv4") enableIpv4: Option[Boolean] = scala.None,
  /* Attach an IPv6 on the public NIC. If false, no IPv6 address will be attached. */
  @named("enable_ipv6") enableIpv6: Option[Boolean] = scala.None,
  /* ID of the ipv4 Primary IP to use. If omitted and enable_ipv4 is true, a new ipv4 Primary IP will automatically be created. */
  @named("ipv4") ipv4: Option[Int] = scala.None,
  /* ID of the ipv6 Primary IP to use. If omitted and enable_ipv6 is true, a new ipv6 Primary IP will automatically be created. */
  @named("ipv6") ipv6: Option[Int] = scala.None
)

