/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * CreateVolumeRequest
   * Request for POST https://api.hetzner.cloud/v1/volumes
   */
case class CreateVolumeRequest(
  /* Auto-mount Volume after attach. `server` must be provided. */
  @named("automount") automount: Option[Boolean] = scala.None,
  /* Format Volume after creation. One of: `xfs`, `ext4`. */
  @named("format") format: Option[String] = scala.None,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Option[Map[String, String]] = scala.None,
  /* Location to create the Volume in (can be omitted if Server is specified). */
  @named("location") location: Option[String] = scala.None,
  /* Name of the volume. */
  @named("name") name: String,
  /* Server to which to attach the Volume once it's created (Volume will be created in the same Location as the server). */
  @named("server") server: Option[Long] = scala.None,
  /* Size of the Volume in GB. */
  @named("size") size: Int
)

