/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * CreateServerResponse
   * Response to POST https://api.hetzner.cloud/v1/servers
   */
case class CreateServerResponse(
  @named("action") action: Action,
  @named("next_actions") nextActions: Seq[Action],
  /* Root password when no SSH keys have been specified. */
  @named("root_password") rootPassword: String,
  @named("server") server: Server
)

