/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Information about the Server the Image was created from.
   */
case class CreatedFrom(
  /* ID of the Server the Image was created from. */
  @named("id") id: Long,
  /* Server name at the time the Image was created. */
  @named("name") name: String
)

