/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Server Types supported and available in this Data Center.
  */
case class DataCenterServerTypes(
    /* Server Types currently available in this Data Center.  These Server Types can currently be purchased. Types that are temporarily unavailable but are supported in this Data Center are listed as `supported`.  */
    @named("available") available: Seq[Long],
    /* Server Types available to migrate to in this Data Center.  Existing Servers can be migrated to these Server Types.  */
    @named("available_for_migration") availableForMigration: Seq[Long],
    /* List of Server Types supported in this Data Center.  These Server Types are generally available in this Data Center, but might be temporarily out of stock.  */
    @named("supported") supported: Seq[Long]
)
