/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Data Center the Primary IP is located at. | Data Center this Resource is
  * located at.
  */
case class DataCenter(
    /* Descriptive name for the Data Center.  Desired to be easy to understand for humans. Might be changed for cosmetic reasons. Do not use this as an identifier.  */
    @named("description") description: String,
    /* ID of the Data Center. */
    @named("id") id: Long,
    @named("location") location: Location,
    /* Unique name for the Data Center.  Can be used as a more descriptive identifier.  */
    @named("name") name: String,
    @named("server_types") serverTypes: DataCenterServerTypes
)
