/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** DeleteSubnetRequest Request for POST
  * https://api.hetzner.cloud/v1/networks/{id}/actions/delete_subnet
  */
case class DeleteSubnetFromNetworkRequest(
    /* IP range in CIDR block notation of the subnet to delete. */
    @named("ip_range") ipRange: String
)
