/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Request for POST
  * https://api.hetzner.cloud/v1/load_balancers/{id}/actions/delete_service
  */
case class DeleteServiceRequest(
    /* The listen port of the service you want to delete. */
    @named("listen_port") listenPort: Int
)
