/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** DeprecationInfo Describes if, when and how the resource is deprecated. If
  * this field is set to `null` the resource is not deprecated. If a value is
  * set, it is considered deprecated. | This field is deprecated. Use the
  * `deprecation` object in the `locations` field instead
  * (`.locations[].deprecation`).
  */
case class DeprecationInfo(
    /* Date of the deprecation announcement.  */
    @named("announced") announced: String,
    /* Date of the deprecated resource removal.  Once this date is reached, the resource will not be returned by resource type \"list\" endpoint, and the resource can not be used to create new resources. For example, if this is an image, you can not create new servers with this image after the mentioned date.  */
    @named("unavailable_after") unavailableAfter: String
)
