/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Request for POST
  * https://api.hetzner.cloud/v1/servers/{id}/actions/enable_rescue
  */
case class EnableRescueModeForServerRequest(
    /* Array of SSH key IDs which should be injected into the rescue system. */
    @named("ssh_keys") sshKeys: Option[Seq[Long]] = scala.None,
    /* Type of rescue system to boot. */
    @named("type") `type`: Option[EnableRescueModeForServerRequestEnums.Type] =
      scala.None
)

object EnableRescueModeForServerRequestEnums:
  enum Type:
    case `linux64`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "linux64" => "linux64"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end EnableRescueModeForServerRequestEnums
