/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Error message for the Action if an error occurred, otherwise null.
  */
case class Error(
    /* Fixed error code for machines. */
    @named("code") code: String,
    /* Error message for humans. */
    @named("message") message: String
)
