/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** FirewallResponse Firewalls can limit the network access to or from your
  * resources.
  */
case class Firewall(
    @named("applied_to") appliedTo: Seq[FirewallResourceId],
    /* Point in time when the Resource was created (in ISO-8601 format). */
    @named("created") created: String,
    /* ID of the Firewall. */
    @named("id") id: Long,
    /* Name of the Firewall.  Limited to a maximum of 128 characters.  Must be unique per Project.  */
    @named("name") name: String,
    @named("rules") rules: Seq[RuleResponse],
    /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
    @named("labels") labels: Option[Map[String, String]] = scala.None
)
