/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Resource a Firewall should be applied to.
   */
case class FirewallResourceId(
  /* The type of resource to apply. */
  @named("type") `type`: FirewallResourceIdEnums.Type,
  /* Resources applied to via this Label Selector.  */
  @named("applied_to_resources") appliedToResources: Option[Seq[FirewallResourceIdAppliedToResources]] = scala.None,
  @named("label_selector") labelSelector: Option[LabelSelector] = scala.None,
  @named("server") server: Option[ResourceId] = scala.None
)

object FirewallResourceIdEnums:
  enum Type:
    case `label_selector`
    case `server`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "label_selector" => "label_selector"
            case "server" => "server"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end FirewallResourceIdEnums
