/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import hcloud.models.IpType.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class FloatingIp(
    /* Indicates whether the Floating IP is blocked. */
    @named("blocked") blocked: Boolean,
    /* Point in time when the Resource was created (in ISO-8601 format). */
    @named("created") created: String,
    /* Description of the Resource. */
    @named("description") description: String,
    /* List of reverse DNS entries for the Floating IP.  */
    @named("dns_ptr") dnsPtr: Seq[DnsPtr],
    @named("home_location") homeLocation: Location,
    /* ID of the Floating IP. */
    @named("id") id: Long,
    /* IP address. */
    @named("ip") ip: String,
    /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
    @named("labels") labels: Map[String, String],
    /* Name of the Resource. Must be unique per Project. */
    @named("name") name: String,
    @named("protection") protection: Protection,
    /* Server the Floating IP is assigned to.  `null` if not assigned.  */
    @named("server") server: Long,
    @named("type") `type`: IpType
)

object FloatingIpEnums:
end FloatingIpEnums
