/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Response to GET https://api.hetzner.cloud/v1/load_balancer_types/{id}
   */
case class GetLoadBalancerTypeResponse(
  @named("load_balancer_type") loadBalancerType: Option[LoadBalancerType] = scala.None
)

