/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** PlacementGroupResponse Response to GET
  * https://api.hetzner.cloud/v1/placement_groups/{id}
  */
case class GetPlacementgroupResponse(
    @named("placement_group") placementGroup: PlacementGroup
)
