/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Response to GET https://api.hetzner.com/v1/storage_boxes/{id}/subaccounts/{subaccount_id}
   */
case class GetSubaccountResponse(
  @named("subaccount") subaccount: Subaccount
)

