/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** LoadBalancerServiceHTTP Configuration option for protocols http and https.
  */
case class Http(
    /* IDs of the Certificates to use for TLS/SSL termination by the Load Balancer; empty for TLS/SSL passthrough or if `protocol` is `http`. */
    @named("certificates") certificates: Option[Seq[Long]] = scala.None,
    /* Lifetime of the cookie used for sticky sessions (in seconds). */
    @named("cookie_lifetime") cookieLifetime: Option[Int] = scala.None,
    /* Name of the cookie used for sticky sessions. */
    @named("cookie_name") cookieName: Option[String] = scala.None,
    /* Redirect HTTP requests to HTTPS. Only available if `protocol` is `https`. */
    @named("redirect_http") redirectHttp: Option[Boolean] = scala.None,
    /* Use sticky sessions. Only available if `protocol` is `http` or `https`. */
    @named("sticky_sessions") stickySessions: Option[Boolean] = scala.None
)
