/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Request for POST https://api.hetzner.cloud/v1/zones/{id_or_name}/actions/import_zonefile
   */
case class ImportZoneFileRequest(
  /* Zone file to import.  See Zone file import for more details.  */
  @named("zonefile") zonefile: String
)

