/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * IPv6 network assigned to this Server and its reverse DNS entry.
   */
case class Ipv6(
  /* If the IP is blocked by our anti abuse dept. */
  @named("blocked") blocked: Boolean,
  /* Reverse DNS PTR entries for the IPv6 addresses of this Server. */
  @named("dns_ptr") dnsPtr: Seq[DnsPtr],
  /* ID of the Primary IP. */
  @named("id") id: Option[Long] = scala.None,
  /* IP address (v6) of this Server. */
  @named("ip") ip: String
)

