/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import hcloud.models.Architecture.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** ISO Image that is attached to this Server. Null if no ISO is attached.
  */
case class Iso(
    /* CPU architecture compatible with the ISO.  Null indicates no restriction on the architecture (wildcard).  */
    @named("architecture") architecture: Architecture,
    /* Describes if, when and how the resource is deprecated. If this field is set to `null` the resource is not deprecated. If a value is set, it is considered deprecated.  */
    @named("deprecation") deprecation: DeprecationInfo,
    /* Description of the ISO. */
    @named("description") description: String,
    /* ID of the ISO. */
    @named("id") id: Long,
    /* Unique identifier of the ISO. Only set for public ISOs. */
    @named("name") name: String,
    /* Type of the ISO. */
    @named("type") `type`: IsoEnums.Type
)

object IsoEnums:
  enum Type:
    case `private`
    case `public`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "private" => "private"
            case "public"  => "public"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end IsoEnums
