/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import scala.math.BigDecimal
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class ListPricesResponsePricing(
  /* Currency the returned prices are expressed in, coded according to [ISO 4217](https://wikipedia.org/wiki/ISO_4217). */
  @named("currency") currency: String,
  @named("floating_ip") floatingIp: ListPricesResponsePricingFloatingIp,
  /* Price of Floating IPs per type and per Location. */
  @named("floating_ips") floatingIps: Seq[ListPricesResponsePricingFloatingIps],
  @named("image") image: ListPricesResponsePricingImage,
  /* Price of Load Balancer per type and per Location. */
  @named("load_balancer_types") loadBalancerTypes: Seq[ListPricesResponsePricingLoadBalancerTypes],
  /* Price of Primary IPs per type and per Location. */
  @named("primary_ips") primaryIps: Seq[ListPricesResponsePricingPrimaryIps],
  @named("server_backup") serverBackup: ListPricesResponsePricingServerBackup,
  /* Price of Server per type and per Location. */
  @named("server_types") serverTypes: Seq[ListPricesResponsePricingServerTypes],
  /* VAT rate used for calculating prices with VAT. */
  @named("vat_rate") vatRate: BigDecimal,
  @named("volume") volume: ListPricesResponsePricingVolume
)

