/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import scala.math.BigDecimal
import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Price of Server backups.
   */
case class ListPricesResponsePricingServerBackup(
  /* Price increase of the Server base price in percentage. */
  @named("percentage") percentage: BigDecimal
)

