/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * LoadBalancerService
   * A service for a Load Balancer.
   */
case class LoadBalancerService(
  /* Port the Load Balancer will balance to. */
  @named("destination_port") destinationPort: Int,
  @named("health_check") healthCheck: LoadBalancerServiceHealthCheck,
  /* Port the Load Balancer listens on. */
  @named("listen_port") listenPort: Int,
  /* Protocol of the Load Balancer. */
  @named("protocol") protocol: LoadBalancerServiceEnums.Protocol,
  /* Is Proxyprotocol enabled or not. */
  @named("proxyprotocol") proxyprotocol: Boolean,
  @named("http") http: Option[Http] = scala.None
)

object LoadBalancerServiceEnums:
  enum Protocol:
    case `http`
    case `https`
    case `tcp`

  object Protocol:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given protocolCodec: JsonValueCodec[Protocol] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "http" => "http"
            case "https" => "https"
            case "tcp" => "tcp"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end LoadBalancerServiceEnums
