/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * IP address (v4).
   */
case class LoadBalancerPublicNetIpv4(
  /* Reverse DNS PTR entry for the IPv4 address of this Load Balancer. */
  @named("dns_ptr") dnsPtr: Option[String] = scala.None,
  /* IP address (v4) of this Load Balancer. */
  @named("ip") ip: Option[String] = scala.None
)

