/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** LoadBalancerAlgorithm Algorithm of the Load Balancer.
  */
case class LoadBalancerAlgorithm(
    /* Type of the algorithm. */
    @named("type") `type`: LoadBalancerAlgorithmEnums.Type
)

object LoadBalancerAlgorithmEnums:
  enum Type:
    case `least_connections`
    case `round_robin`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "least_connections" => "least_connections"
            case "round_robin"       => "round_robin"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end LoadBalancerAlgorithmEnums
