/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** LoadBalancerTargetTarget Resolved label selector target Servers. Only
  * present for type \"label_selector\".
  */
case class LoadBalancerSelectedTarget(
    /* List of health statuses of the services on this target. Only present for target types \"server\" and \"ip\". */
    @named("health_status") healthStatus: Option[
      Seq[LoadBalancerTargetHealthStatus]
    ] = scala.None,
    @named("server") server: Option[ResourceId] = scala.None,
    /* Type of the resource. Here always \"server\". */
    @named("type") `type`: Option[String] = scala.None,
    /* Use the private network IP instead of the public IP. Only present for target types \"server\" and \"label_selector\". */
    @named("use_private_ip") usePrivateIp: Option[Boolean] = scala.None
)
