/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Health status of the services on this target. Only present for target types
  * \"server\" and \"ip\".
  */
case class LoadBalancerTargetHealthStatus(
    @named("listen_port") listenPort: Option[Int] = scala.None,
    @named("status") status: Option[
      LoadBalancerTargetHealthStatusEnums.Status
    ] = scala.None
)

object LoadBalancerTargetHealthStatusEnums:
  enum Status:
    case `healthy`
    case `unhealthy`
    case `unknown`

  object Status:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given statusCodec: JsonValueCodec[Status] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "healthy"   => "healthy"
            case "unhealthy" => "unhealthy"
            case "unknown"   => "unknown"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end LoadBalancerTargetHealthStatusEnums
