/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class LoadBalancer(
  @named("algorithm") algorithm: LoadBalancerAlgorithm,
  /* Point in time when the Resource was created (in ISO-8601 format). */
  @named("created") created: String,
  /* ID of the Load Balancer. */
  @named("id") id: Long,
  /* Free Traffic for the current billing period in bytes. */
  @named("included_traffic") includedTraffic: Long,
  /* Inbound Traffic for the current billing period in bytes. */
  @named("ingoing_traffic") ingoingTraffic: Long,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Map[String, String],
  @named("load_balancer_type") loadBalancerType: LoadBalancerType,
  @named("location") location: Location,
  /* Name of the Resource. Must be unique per Project. */
  @named("name") name: String,
  /* Outbound Traffic for the current billing period in bytes. */
  @named("outgoing_traffic") outgoingTraffic: Long,
  /* Private networks information. */
  @named("private_net") privateNet: Seq[LoadBalancerPrivateNet],
  @named("protection") protection: Protection,
  @named("public_net") publicNet: LoadBalancerPublicNet,
  /* List of services that belong to this Load Balancer. */
  @named("services") services: Seq[LoadBalancerService],
  /* List of targets that belong to this Load Balancer. */
  @named("targets") targets: Seq[LoadBalancerTarget]
)

