/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * LoadBalancerTarget
   * A target of a Load Balancer.
   */
case class LoadBalancerTarget(
  /* Type of the resource. */
  @named("type") `type`: LoadBalancerTargetEnums.Type,
  /* List of health statuses of the services on this target. Only present for target types \"server\" and \"ip\". */
  @named("health_status") healthStatus: Option[Seq[LoadBalancerTargetHealthStatus]] = scala.None,
  @named("ip") ip: Option[LoadBalancerTargetIp] = scala.None,
  @named("label_selector") labelSelector: Option[LabelSelector] = scala.None,
  @named("server") server: Option[ResourceId] = scala.None,
  /* List of resolved label selector target Servers. Only present for type \"label_selector\". */
  @named("targets") targets: Option[Seq[LoadBalancerSelectedTarget]] = scala.None,
  /* Use the private network IP instead of the public IP. Only present for target types \"server\" and \"label_selector\". */
  @named("use_private_ip") usePrivateIp: Option[Boolean] = scala.None
)

object LoadBalancerTargetEnums:
  enum Type:
    case `ip`
    case `label_selector`
    case `server`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "ip" => "ip"
            case "label_selector" => "label_selector"
            case "server" => "server"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end LoadBalancerTargetEnums
