/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * LoadBalancerServiceHealthCheck
   * Service health check.
   */
case class LoadBalancerServiceHealthCheck(
  @named("http") http: Option[LoadBalancerServiceHealthCheckHttp] = scala.None,
  /* Time interval in seconds health checks are performed. */
  @named("interval") interval: Int,
  /* Port the health check will be performed on. */
  @named("port") port: Int,
  /* Type of the health check. */
  @named("protocol") protocol: LoadBalancerServiceHealthCheckEnums.Protocol,
  /* Unsuccessful retries needed until a target is considered unhealthy; an unhealthy target needs the same number of successful retries to become healthy again. */
  @named("retries") retries: Int,
  /* Time in seconds after an attempt is considered a timeout. */
  @named("timeout") timeout: Int
)

object LoadBalancerServiceHealthCheckEnums:
  enum Protocol:
    case `http`
    case `tcp`

  object Protocol:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given protocolCodec: JsonValueCodec[Protocol] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "http" => "http"
            case "tcp" => "tcp"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end LoadBalancerServiceHealthCheckEnums
