/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** You must specify the type of metric to get: open_connections,
  * requests_per_second or bandwidth. You can also specify more than one type by
  * comma separation, e.g. requests_per_second,bandwidth. Depending on the type
  * you will get different time series data.
  */
case class Metrics(
    /* End of period of metrics reported (in ISO-8601 format). */
    @named("end") end: String,
    /* Start of period of metrics reported (in ISO-8601 format). */
    @named("start") start: String,
    /* Resolution of results in seconds. */
    @named("step") step: Int,
    /* Hash with timeseries information, containing the name of timeseries as key. */
    @named("time_series") timeSeries: Map[String, MetricsTimeSeriesValue]
)
