/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Primary nameserver that returns Zones via `AXFR`. Must allow queries from
  * and may send `NOTIFY` queries to [Hetzner's secondary
  * nameservers](https://docs.hetzner.com/dns-console/dns/general/authoritative-name-servers#secondary-dns-servers-old-name-servers-for-robot-customers).
  */
case class Nameserver(
    /* Public IPv4 or IPv6 address of the primary nameserver. */
    @named("address") address: String,
    /* Port of the primary nameserver. */
    @named("port") port: Option[Int] = scala.None,
    /* [Transaction signature (TSIG)](https://en.wikipedia.org/wiki/TSIG) algorithm used to generate the TSIG key.  */
    @named("tsig_algorithm") tsigAlgorithm: Option[
      NameserverEnums.TsigAlgorithm
    ] = scala.None,
    /* [Transaction signature (TSIG)](https://en.wikipedia.org/wiki/TSIG) key to use for the zone transfer. Must be base64 encoded.  */
    @named("tsig_key") tsigKey: Option[String] = scala.None
)

object NameserverEnums:
  enum TsigAlgorithm:
    case `hmac-md5`
    case `hmac-sha1`
    case `hmac-sha256`

  object TsigAlgorithm:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given tsigAlgorithmCodec: JsonValueCodec[TsigAlgorithm] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "hmac-md5"    => "hmac-md5"
              case "hmac-sha1"   => "hmac-sha1"
              case "hmac-sha256" => "hmac-sha256"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end NameserverEnums
