/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Network(
  /* Point in time when the Resource was created (in ISO-8601 format). */
  @named("created") created: String,
  /* Indicates if the routes from this Network should be exposed to the vSwitch connection. */
  @named("expose_routes_to_vswitch") exposeRoutesToVswitch: Boolean,
  /* ID of the Network. */
  @named("id") id: Long,
  /* IP range of the Network.  Uses CIDR notation.  */
  @named("ip_range") ipRange: String,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Map[String, String],
  /* Array of IDs of Load Balancers attached to this Network. */
  @named("load_balancers") loadBalancers: Option[Seq[Long]] = scala.None,
  /* Name of the Network. */
  @named("name") name: String,
  @named("protection") protection: Protection,
  /* Array of routes set in this Network. */
  @named("routes") routes: Seq[Route],
  /* Array of IDs of Servers attached to this Network. */
  @named("servers") servers: Seq[Long],
  /* List of subnets allocated in this Network. */
  @named("subnets") subnets: Seq[SubnetWithGateway]
)

