/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class PricePerTimeWithoutTraffic(
  /* Name of the Location the price is for. */
  @named("location") location: String,
  @named("price_hourly") priceHourly: Price,
  @named("price_monthly") priceMonthly: Price
)

