/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import scala.math.BigDecimal
import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Hourly price in this Location. | Monthly price in this Location. | Additional traffic price per TB in this Location. | Price of Images per GB/month. | Price of Volumes per GB/month. | Price of one Floating IP per month. | Setup fee in this Location.
   */
case class Price(
  /* Price with VAT added. */
  @named("gross") gross: BigDecimal,
  /* Price without VAT. */
  @named("net") net: BigDecimal
)

