/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Response to POST https://api.hetzner.cloud/v1/servers/{id}/actions/rebuild
  */
case class RebuildServerFromImageResponse(
    @named("action") action: Option[Action] = scala.None,
    /* New root password when not using SSH keys. */
    @named("root_password") rootPassword: Option[String] = scala.None
)
