/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Response to PUT
  * https://api.hetzner.com/v1/storage_boxes/{id}/snapshots/{snapshot_id}
  */
case class ReplaceSnapshotResponse(
    @named("snapshot") snapshot: Snapshot
)
