/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * NetworkUpdateRequest
   * Request for PUT https://api.hetzner.cloud/v1/networks/{id}
   */
case class ReplaceNetworkRequest(
  /* Toggle to expose routes to the Networks vSwitch.  Indicates if the routes from this Network should be exposed to the vSwitch in this Network. Only takes effect if a [vSwitch is setup](https://docs.hetzner.com/cloud/networks/connect-dedi-vswitch) in this Network.  */
  @named("expose_routes_to_vswitch") exposeRoutesToVswitch: Option[Boolean] = scala.None,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Option[Map[String, String]] = scala.None,
  /* New Network name. */
  @named("name") name: Option[String] = scala.None
)

