/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * FloatingIPUpdateRequest
   * Request for PUT https://api.hetzner.cloud/v1/floating_ips/{id}
   */
case class ReplaceFloatingIpRequest(
  /* Description of the Resource. */
  @named("description") description: Option[String] = scala.None,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Option[Map[String, String]] = scala.None,
  /* Name of the Resource. Must be unique per Project. */
  @named("name") name: Option[String] = scala.None
)

