/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Response to POST https://api.hetzner.cloud/v1/servers/{id}/actions/request_console
   */
case class RequestConsoleForServerResponse(
  @named("action") action: Action,
  /* VNC password to use for this connection (this password only works in combination with a wss_url with valid token). */
  @named("password") password: String,
  /* URL of websocket proxy to use; this includes a token which is valid for a limited time only. */
  @named("wss_url") wssUrl: String
)

