/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Resource(
    /* ID of the Resource. | ID of resource referenced. */
    @named("id") id: Long,
    /* Type of the Resource. | Type of resource referenced. */
    @named("type") `type`: String
)
