/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Type of the RRSet.
  */

enum ResourceRecordSetType:
  case `A`
  case `AAAA`
  case `CAA`
  case `CNAME`
  case `DS`
  case `HINFO`
  case `HTTPS`
  case `MX`
  case `NS`
  case `PTR`
  case `RP`
  case `SOA`
  case `SRV`
  case `SVCB`
  case `TLSA`
  case `TXT`

object ResourceRecordSetType:
  import com.github.plokhotnyuk.jsoniter_scala.macros.*
  import com.github.plokhotnyuk.jsoniter_scala.core.*
  given resourceRecordSetTypeCodec: JsonValueCodec[ResourceRecordSetType] =
    JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "A"     => "A"
            case "AAAA"  => "AAAA"
            case "CAA"   => "CAA"
            case "CNAME" => "CNAME"
            case "DS"    => "DS"
            case "HINFO" => "HINFO"
            case "HTTPS" => "HTTPS"
            case "MX"    => "MX"
            case "NS"    => "NS"
            case "PTR"   => "PTR"
            case "RP"    => "RP"
            case "SOA"   => "SOA"
            case "SRV"   => "SRV"
            case "SVCB"  => "SVCB"
            case "TLSA"  => "TLSA"
            case "TXT"   => "TXT"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end ResourceRecordSetType
