/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Record
   * Record of a RRSet.  The `value` is used to identify the record in an RRSet. 
   */
case class ResourceRecord(
  /* Comment of the record. */
  @named("comment") comment: Option[String] = scala.None,
  /* Value of the record.  For details about accepted values, see the [DNS record types documentation](https://docs.hetzner.com/networking/dns/record-types/overview/).  */
  @named("value") value: String
)

