/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Request for POST https://api.hetzner.com/v1/storage_boxes/{id}/actions/rollback_snapshot
   */
case class RollbackSnapshotRequest(
  /* ID or Name of the Storage Box Snapshot. */
  @named("snapshot") snapshot: String
)

