/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Request for POST https://api.hetzner.cloud/v1/networks/{id}/actions/add_route | Request for POST https://api.hetzner.cloud/v1/networks/{id}/actions/delete_route
   */
case class Route(
  /* Destination network or host of the route.  Packages addressed for IPs matching the destination IP prefix will be send to the specified gateway.  Must be one of * private IPv4 ranges of RFC1918 * or `0.0.0.0/0`.  Must not overlap with * an existing ip_range in any subnets * or with any destinations in other routes * or with `172.31.1.1`.  `172.31.1.1` is being used as a gateway for the public network interface of Servers.  */
  @named("destination") destination: String,
  /* Gateway of the route.  Packages addressed for the specified destination will be send to this IP address.  Cannot be * the first IP of the networks ip_range, * an IP behind a vSwitch or * `172.31.1.1`.  `172.31.1.1` is being used as a gateway for the public network interface of Servers.  */
  @named("gateway") gateway: String
)

