/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class RuleResponse(
    /* List of permitted IPv4/IPv6 addresses for outgoing traffic.  The `direction` must be set to `out`.  IPs must be in [CIDR block notation](https://wikipedia.org/wiki/CIDR). You can specify 100 CIDR blocks at most.  The CIDR blocks may refer to networks (with empty host bits) or single hosts. For example, a network could be defined with `10.0.1.0/24` or `2001:db8:ff00:42::/64`, and a single host with `10.0.1.1/32` or `2001:db8:ff00:42::8329/128`.  Use `0.0.0.0/0` to allow any IPv4 addresses and `::/0` to allow any IPv6 addresses.  IPv6 CIDRs will be transformed to their canonical form according to [RFC5952](https://datatracker.ietf.org/doc/html/rfc5952#section-4).  */
    @named("destination_ips") destinationIps: Seq[String],
    /* Traffic direction in which the rule should be applied to.  Use `source_ips` for direction `in` and `destination_ips` for direction `out` to specify IPs.  */
    @named("direction") direction: RuleResponseEnums.Direction,
    /* Port or port range to apply the rule for.  Only applicable for protocols `tcp` and `udp`.  A port range can be specified by separating lower and upper bounds with a dash. `1024-5000` will include all ports starting from 1024 up to port 5000.  */
    @named("port") port: String,
    /* Network protocol to apply the rule for. */
    @named("protocol") protocol: RuleResponseEnums.Protocol,
    /* List of permitted IPv4/IPv6 addresses for incoming traffic.  The `direction` must be set to `in`.  IPs must be provided in [CIDR block notation](https://wikipedia.org/wiki/CIDR). You can specify 100 CIDR blocks at most.  The CIDR blocks may refer to networks (with empty host bits) or single hosts. For example, a network could be defined with `10.0.1.0/24` or `2001:db8:ff00:42::/64`, and a single host with `10.0.1.1/32` or `2001:db8:ff00:42::8329/128`.  Use `0.0.0.0/0` to allow any IPv4 addresses and `::/0` to allow any IPv6 addresses.  IPv6 CIDRs will be transformed to their canonical form according to [RFC5952](https://datatracker.ietf.org/doc/html/rfc5952#section-4).  */
    @named("source_ips") sourceIps: Seq[String],
    /* Description of the rule. */
    @named("description") description: Option[String] = scala.None
)

object RuleResponseEnums:
  enum Direction:
    case `in`
    case `out`

  object Direction:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given directionCodec: JsonValueCodec[Direction] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "in"  => "in"
            case "out" => "out"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum Protocol:
    case `esp`
    case `gre`
    case `icmp`
    case `tcp`
    case `udp`

  object Protocol:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given protocolCodec: JsonValueCodec[Protocol] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "esp"  => "esp"
            case "gre"  => "gre"
            case "icmp" => "icmp"
            case "tcp"  => "tcp"
            case "udp"  => "udp"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end RuleResponseEnums
