/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * Servers are virtual machines that can be provisioned.
   */
case class Server(
  /* Time window (UTC) in which the backup will run, or null if the backups are not enabled. */
  @named("backup_window") backupWindow: String,
  /* Point in time when the Resource was created (in ISO-8601 format). */
  @named("created") created: String,
  @named("datacenter") datacenter: DataCenter,
  /* ID of the Server. */
  @named("id") id: Long,
  /* Image the server is based on. */
  @named("image") image: Image,
  /* Free Traffic for the current billing period in bytes. */
  @named("included_traffic") includedTraffic: Long,
  /* Inbound Traffic for the current billing period in bytes. */
  @named("ingoing_traffic") ingoingTraffic: Long,
  /* ISO Image that is attached to this Server. Null if no ISO is attached. */
  @named("iso") iso: Iso,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Map[String, String],
  /* Load Balancer IDs assigned to the server. */
  @named("load_balancers") loadBalancers: Option[Seq[Long]] = scala.None,
  /* True if Server has been locked and is not available to user. */
  @named("locked") locked: Boolean,
  /* Name of the Server (must be unique per Project and a valid hostname as per RFC 1123). */
  @named("name") name: String,
  /* Outbound Traffic for the current billing period in bytes. */
  @named("outgoing_traffic") outgoingTraffic: Long,
  @named("placement_group") placementGroup: Option[PlacementGroupNullable] = scala.None,
  /* Size of the primary Disk. */
  @named("primary_disk_size") primaryDiskSize: Int,
  /* Private networks information. */
  @named("private_net") privateNet: Seq[ServerPrivateNet],
  @named("protection") protection: ServerProtection,
  @named("public_net") publicNet: ServerPublicNet,
  /* True if rescue mode is enabled. Server will then boot into rescue system on next reboot. */
  @named("rescue_enabled") rescueEnabled: Boolean,
  @named("server_type") serverType: ServerType,
  /* Status of the Server. */
  @named("status") status: ServerEnums.Status,
  /* IDs of Volumes assigned to this Server. */
  @named("volumes") volumes: Option[Seq[Long]] = scala.None
)

object ServerEnums:
  enum Status:
    case `deleting`
    case `initializing`
    case `migrating`
    case `off`
    case `rebuilding`
    case `running`
    case `starting`
    case `stopping`
    case `unknown`

  object Status:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given statusCodec: JsonValueCodec[Status] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "deleting" => "deleting"
            case "initializing" => "initializing"
            case "migrating" => "migrating"
            case "off" => "off"
            case "rebuilding" => "rebuilding"
            case "running" => "running"
            case "starting" => "starting"
            case "stopping" => "stopping"
            case "unknown" => "unknown"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end ServerEnums
