/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class ServerPrivateNet(
    /* Additional IP addresses of the server on the network. */
    @named("alias_ips") aliasIps: Option[Seq[String]] = scala.None,
    /* The server IP address on the network. */
    @named("ip") ip: Option[String] = scala.None,
    /* The server MAC address on the network. */
    @named("mac_address") macAddress: Option[String] = scala.None,
    /* The Network ID the server is attached to. */
    @named("network") network: Option[Long] = scala.None
)
