/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import hcloud.models.Architecture.*
import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class ServerType(
  @named("architecture") architecture: Architecture,
  /* Category of Server Type. */
  @named("category") category: Option[String] = scala.None,
  /* Number of cpu cores a Server of this type will have. */
  @named("cores") cores: Int,
  /* Type of cpu. */
  @named("cpu_type") cpuType: ServerTypeEnums.CpuType,
  /* This field is deprecated. Use the deprecation object instead. */
  @named("deprecated") deprecated: Boolean,
  /* This field is deprecated.  Use the `deprecation` object in the `locations` field instead (`.locations[].deprecation`).  */
  @named("deprecation") deprecation: Option[DeprecationInfo] = scala.None,
  /* Description of the Server type. */
  @named("description") description: String,
  /* Disk size a Server of this type will have in GB. */
  @named("disk") disk: Double,
  /* ID of the Server type. */
  @named("id") id: Long,
  /* Supported Location and per Location details for the Server Type.  A Server Type is:  - only supported in the Location that are listed.  - deprecated in the Location when the `deprecation` property is set.  - unavailable in the Location when the `deprecation.unavailable_after` date is in the past.  */
  @named("locations") locations: Seq[ServerTypeLocation],
  /* Memory a Server of this type will have in GB. */
  @named("memory") memory: Double,
  /* Unique identifier of the Server type. */
  @named("name") name: String,
  /* Price per Location. */
  @named("prices") prices: Seq[PricePerTime],
  /* Type of Server boot drive. Local has higher speed. Network has better availability. */
  @named("storage_type") storageType: ServerTypeEnums.StorageType
)

object ServerTypeEnums:
  enum CpuType:
    case `dedicated`
    case `shared`

  object CpuType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given cpuTypeCodec: JsonValueCodec[CpuType] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "dedicated" => "dedicated"
            case "shared" => "shared"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum StorageType:
    case `local`
    case `network`

  object StorageType:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given storageTypeCodec: JsonValueCodec[StorageType] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "local" => "local"
            case "network" => "network"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end ServerTypeEnums
