/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Statistics of the Storage Box Snapshot.
  */
case class SnapshotStats(
    /* Current storage requirements of the Snapshot in bytes. */
    @named("size") size: Long,
    /* Size of the compressed file system contained in the Snapshot in bytes. */
    @named("size_filesystem") sizeFilesystem: Long
)
