/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Snapshot(
  /* Point in time when the Resource was created (in ISO-8601 format). */
  @named("created") created: String,
  /* Description of the Storage Box Snapshot. */
  @named("description") description: String,
  /* ID of the Storage Box Snapshot. */
  @named("id") id: Long,
  /* Whether the Storage Box Snapshot was created automatically. */
  @named("is_automatic") isAutomatic: Boolean,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Map[String, String],
  /* Name of the Storage Box Snapshot. */
  @named("name") name: String,
  @named("stats") stats: SnapshotStats,
  /* ID of the Storage Box. */
  @named("storage_box") storageBox: Long
)

