/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

  /**
   * SSH keys are public keys you provide to the cloud system. They can be injected into Servers at creation time. We highly recommend that you use keys instead of passwords to manage your Servers.
   */
case class SshKey(
  /* Point in time when the Resource was created (in ISO-8601 format). */
  @named("created") created: String,
  /* MD5 fingerprint of the SSH public key. */
  @named("fingerprint") fingerprint: String,
  /* ID of the SSH Key. */
  @named("id") id: Long,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Map[String, String],
  /* Name of the Resource. Must be unique per Project. */
  @named("name") name: String,
  /* Public key. */
  @named("public_key") publicKey: String
)

