/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class StorageBox(
  @named("access_settings") accessSettings: StorageBoxAccessSetting,
  /* Point in time when the Resource was created (in ISO-8601 format). */
  @named("created") created: String,
  /* ID of the Storage Box. */
  @named("id") id: Long,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Map[String, String],
  @named("location") location: Location,
  /* Name of the Storage Box.  */
  @named("name") name: String,
  @named("protection") protection: Protection,
  /* FQDN of the Storage Box.  Not available if the `status` is `initializing`.  */
  @named("server") server: String,
  /* Details of the active snapshot plan.  Not available if the `status` is `initializing`.  */
  @named("snapshot_plan") snapshotPlan: SnapshotPlan,
  @named("stats") stats: StorageBoxStats,
  /* Status of the Storage Box. */
  @named("status") status: StorageBoxEnums.Status,
  @named("storage_box_type") storageBoxType: StorageBoxType,
  /* Host system of the Storage Box.  Not available if the `status` is `initializing`.  */
  @named("system") system: String,
  /* Primary username of the Storage Box.  Not available if the `status` is `initializing`.  */
  @named("username") username: String
)

object StorageBoxEnums:
  enum Status:
    case `active`
    case `initializing`
    case `locked`

  object Status:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given statusCodec: JsonValueCodec[Status] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "active" => "active"
            case "initializing" => "initializing"
            case "locked" => "locked"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end StorageBoxEnums
