/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Statistics of the Storage Box.
  */
case class StorageBoxStats(
    /* Current disk usage in bytes. */
    @named("size") size: Long,
    /* Current disk usage for data in bytes. */
    @named("size_data") sizeData: Long,
    /* Current disk usage for snapshots in bytes. */
    @named("size_snapshots") sizeSnapshots: Long
)
