/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

/** Access settings for the Subaccount.
  */
case class SubaccountAccessSetting(
    /* Whether access from outside the Hetzner network is allowed. */
    @named("reachable_externally") reachableExternally: Boolean,
    /* Whether the Subaccount is read-only. */
    @named("readonly") readonly: Boolean,
    /* Whether the Samba subsystem is enabled. */
    @named("samba_enabled") sambaEnabled: Boolean,
    /* Whether the SSH subsystem is enabled. */
    @named("ssh_enabled") sshEnabled: Boolean,
    /* Whether the WebDAV subsystem is enabled. */
    @named("webdav_enabled") webdavEnabled: Boolean
)
