/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Subaccount(
  @named("access_settings") accessSettings: SubaccountAccessSetting,
  /* Point in time when the Resource was created (in ISO-8601 format). */
  @named("created") created: String,
  /* A description of Storage Box Subaccount.  */
  @named("description") description: String,
  /* Home directory of the Storage Box Subaccount.  */
  @named("home_directory") homeDirectory: String,
  /* ID of the Storage Box Subaccount. */
  @named("id") id: Long,
  /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
  @named("labels") labels: Map[String, String],
  /* FQDN of the Storage Box Subaccount. */
  @named("server") server: String,
  /* ID of the Storage Box. */
  @named("storage_box") storageBox: Long,
  /* Username of the Storage Box Subaccount. */
  @named("username") username: String
)

