/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class SubnetWithGateway(
    /* Gateway for Servers attached to this subnet.  For subnets of type `server` this is always the first IP of the subnets IP range.  */
    @named("gateway") gateway: String,
    /* Name of the Network Zone.  The Location contains the `network_zone` property it belongs to.  */
    @named("network_zone") networkZone: String,
    /* Type of subnet.  - `cloud` - Used to connect cloud Servers and Load Balancers. - `server` - Same as the `cloud` type. **Deprecated**, use the `cloud` type instead. - `vswitch` - Used to [connect cloud Servers and Load Balancers with dedicated Servers](https://docs.hetzner.com/cloud/networks/connect-dedi-vswitch).  */
    @named("type") `type`: SubnetWithGatewayEnums.Type,
    /* IP range of the subnet.  Uses CIDR notation.  */
    @named("ip_range") ipRange: Option[String] = scala.None,
    /* ID of the robot vSwitch if the subnet is of type `vswitch`. */
    @named("vswitch_id") vswitchId: Option[Long] = scala.None
)

object SubnetWithGatewayEnums:
  enum Type:
    case `cloud`
    case `server`
    case `vswitch`

  object Type:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given typeCodec: JsonValueCodec[Type] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "cloud"   => "cloud"
            case "server"  => "server"
            case "vswitch" => "vswitch"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end SubnetWithGatewayEnums
