/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class Zone(
    @named(
      "authoritative_nameservers"
    ) authoritativeNameservers: ZoneAuthoritativeNameservers,
    /* Point in time when the Resource was created (in ISO-8601 format). */
    @named("created") created: String,
    /* ID of the Zone. */
    @named("id") id: Long,
    /* User-defined labels (`key/value` pairs) for the Resource. For more information, see \"Labels\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of Labels provided in the request will overwrite the existing one.  For more information, see \"Labels\".  */
    @named("labels") labels: Map[String, String],
    /* Mode of the Zone.  For more information, see Zone Modes.  */
    @named("mode") mode: ZoneEnums.Mode,
    /* Name of the Zone.  All names with [well-known public suffixes](https://publicsuffix.org/) (e.g. `.de`, `.com`, `.co.uk`) are supported. Subdomains are not supported.  The name must be in lower case and must not end with a dot. [Internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) must be transcribed to [Punycode](https://wikipedia.org/wiki/Punycode) representation with ACE prefix, e.g. `xn--mnchen-3ya.de` (`münchen.de`).  */
    @named("name") name: String,
    @named("protection") protection: Protection,
    /* Number of resource records (RR) within the Zone. */
    @named("record_count") recordCount: Int,
    /* Registrar of the domain. */
    @named("registrar") registrar: ZoneEnums.Registrar,
    /* Status of the Zone.  - `ok`: the Zone is pushed to the authoritative nameservers. - `updating`: the Zone is currently being published to the authoritative nameservers. - `error`: the Zone could not be published to the authoritative nameservers.  */
    @named("status") status: ZoneEnums.Status,
    /* Default Time To Live (TTL) of the Zone.  Must be in between 60s and 2147483647s.  This TTL is used for RRSets that do not explicitly define a TTL.  */
    @named("ttl") ttl: Int,
    /* Primary nameservers of the Zone.  Only set if Zone is in secondary mode, otherwise empty.  */
    @named("primary_nameservers") primaryNameservers: Option[Seq[Nameserver]] =
      scala.None
)

object ZoneEnums:
  enum Mode:
    case `primary`
    case `secondary`

  object Mode:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given modeCodec: JsonValueCodec[Mode] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "primary"   => "primary"
            case "secondary" => "secondary"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum Registrar:
    case `hetzner`
    case `other`
    case `unknown`

  object Registrar:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given registrarCodec: JsonValueCodec[Registrar] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "hetzner" => "hetzner"
            case "other"   => "other"
            case "unknown" => "unknown"
        }
        .withDiscriminatorFieldName(scala.None)
    }
  enum Status:
    case `error`
    case `ok`
    case `updating`

  object Status:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given statusCodec: JsonValueCodec[Status] = JsonCodecMaker.make {
      CodecMakerConfig
        .withAdtLeafClassNameMapper { x =>
          JsonCodecMaker.simpleClassName(x) match
            case "error"    => "error"
            case "ok"       => "ok"
            case "updating" => "updating"
        }
        .withDiscriminatorFieldName(scala.None)
    }
end ZoneEnums
