/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.models

import com.github.plokhotnyuk.jsoniter_scala.macros.named

case class ZoneAuthoritativeNameservers(
    /* Authoritative Hetzner nameservers assigned to this Zone.  */
    @named("assigned") assigned: Seq[String],
    /* Authoritative nameservers currently delegated to by the parent DNS zone.  If these don't match the assigned authoritative nameservers, the DNS zone is currently not being served by Hetzner.  */
    @named("delegated") delegated: Seq[String],
    /* Point in time (in ISO-8601 format) when the DNS zone delegation was last checked.  */
    @named("delegation_last_check") delegationLastCheck: String,
    /* Status of the delegation.  - `valid` - Parent zone correctly delegates to assigned nameservers. - `partially-valid` - Parent zone delegates to additional Hetzner nameservers not assigned to this zone. - `invalid` - Parent zone does not delegate to the assigned nameservers. - `lame` - Parent zone delegates to nameservers that don't know the zone. - `unregistered` - Domain is not registered. - `unknown` - Not yet known.  */
    @named("delegation_status") delegationStatus: Option[
      ZoneAuthoritativeNameserversEnums.DelegationStatus
    ] = scala.None
)

object ZoneAuthoritativeNameserversEnums:
  enum DelegationStatus:
    case `invalid`
    case `lame`
    case `partially-valid`
    case `unknown`
    case `unregistered`
    case `valid`

  object DelegationStatus:
    import com.github.plokhotnyuk.jsoniter_scala.macros.*
    import com.github.plokhotnyuk.jsoniter_scala.core.*
    given delegationStatusCodec: JsonValueCodec[DelegationStatus] =
      JsonCodecMaker.make {
        CodecMakerConfig
          .withAdtLeafClassNameMapper { x =>
            JsonCodecMaker.simpleClassName(x) match
              case "invalid"         => "invalid"
              case "lame"            => "lame"
              case "partially-valid" => "partially-valid"
              case "unknown"         => "unknown"
              case "unregistered"    => "unregistered"
              case "valid"           => "valid"
          }
          .withDiscriminatorFieldName(scala.None)
      }
end ZoneAuthoritativeNameserversEnums
