/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.api

import hcloud.models.GetActionResponse
import hcloud.models.GetMultipleActionsResponse
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object Actions:
  def apply(
      baseUrl: String = "https://api.hetzner.cloud/v1"
  ): Actions[hcloud.Authorization.NoAuthorization.type] =
    Actions(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): Actions[hcloud.Authorization.BasicAuth] =
    Actions(baseUrl, hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): Actions[hcloud.Authorization.ApiKey] =
    Actions(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): Actions[hcloud.Authorization.BearerToken] =
    Actions(baseUrl, hcloud.Authorization.BearerToken(token))

case class Actions[Auth <: hcloud.Authorization] private (
    baseUrl: String,
    authConfig: hcloud.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): Actions[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): Actions[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: Actions[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): Actions[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /** Returns a specific Action object.
    *
    * Expected answers: code 200 : GetActionResponse (Response for getting an
    * Action.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Action.
    */
  def getAction(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetActionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/actions/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /** Returns multiple Action objects specified by the `id` parameter. **Note**:
    * This endpoint previously allowed listing all actions in the project. This
    * functionality was deprecated in July 2023 and removed on 30 January 2025. -
    * Announcement:
    * https://docs.hetzner.cloud/changelog#2023-07-20-actions-list-endpoint-is-deprecated -
    * Removal:
    * https://docs.hetzner.cloud/changelog#2025-01-30-listing-arbitrary-actions-in-the-actions-list-endpoint-is-removed
    *
    * Expected answers: code 200 : GetMultipleActionsResponse (Response for
    * listing Actions.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   Filter the actions by ID. Can be used multiple times. The response will
    *   only contain actions matching the specified IDs.
    */
  def getMultipleActions(id: Seq[Long])(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetMultipleActionsResponse]
  ] =
    val requestURL =
      uri"$baseUrl/actions"
        .addParams(
          FormSerializable.serialize("id", id, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetMultipleActionsResponse])

end Actions
