/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.api

import hcloud.models.AssignFloatingIpToServerRequest
import hcloud.models.AssignFloatingIpToServerResponse
import hcloud.models.ChangeFloatingIpProtectionResponse
import hcloud.models.ChangeReverseDnsRecordsForFloatingIpResponse
import hcloud.models.CreateFloatingIpRequest
import hcloud.models.CreateFloatingIpResponse
import hcloud.models.DnsPtr
import hcloud.models.GetActionResponse
import hcloud.models.GetFloatingIpResponse
import hcloud.models.ListActionsResponse
import hcloud.models.ListFloatingIpsResponse
import hcloud.models.Protection
import hcloud.models.ReplaceFloatingIpRequest
import hcloud.models.ReplaceFloatingIpResponse
import hcloud.models.UnassignFloatingIpResponse
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object FloatingIps:
  def apply(baseUrl: String = "https://api.hetzner.cloud/v1"): FloatingIps[hcloud.Authorization.NoAuthorization.type] = FloatingIps(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(baseUrl: String, username: String, password: String): FloatingIps[hcloud.Authorization.BasicAuth] =
    FloatingIps(baseUrl, hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(baseUrl: String, apiKey: String): FloatingIps[hcloud.Authorization.ApiKey] =
    FloatingIps(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(baseUrl: String, token: String): FloatingIps[hcloud.Authorization.BearerToken] =
    FloatingIps(baseUrl, hcloud.Authorization.BearerToken(token))

case class FloatingIps[Auth <: hcloud.Authorization] private (baseUrl: String, authConfig: hcloud.Authorization):
  def withBasicAuth(username: String, password: String): FloatingIps[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): FloatingIps[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: FloatingIps[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(token: String): FloatingIps[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /**
   * Assigns a Floating IP to a Server. 
   * 
   * Expected answers:
   *   code 201 : AssignFloatingIpToServerResponse (Response for assigning a Floating IP.  Contains an Action of type `assign_floating_ip`. )
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Floating IP.
   * @param assignFloatingIpToServerRequest 
   */
  def assignFloatingIpToServer(id: Long, assignFloatingIpToServerRequest: AssignFloatingIpToServerRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], AssignFloatingIpToServerResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/floating_ips/${idPathParam}/actions/assign"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(assignFloatingIpToServerRequest))
      .response(asJson[AssignFloatingIpToServerResponse])

  /**
   * Changes the protection settings configured for the Floating IP. 
   * 
   * Expected answers:
   *   code 201 : ChangeFloatingIpProtectionResponse (Response for changing a Floating IPs protection settings.  Contains an Action of type `change_protection`. )
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Floating IP.
   * @param body 
   */
  def changeFloatingIpProtection(id: Long, body: Protection)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ChangeFloatingIpProtectionResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/floating_ips/${idPathParam}/actions/change_protection"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(body))
      .response(asJson[ChangeFloatingIpProtectionResponse])

  /**
   * Change the reverse DNS records for this Floating IP.  Allows to modify the PTR records set for the IP address. 
   * 
   * Expected answers:
   *   code 201 : ChangeReverseDnsRecordsForFloatingIpResponse (Response for changing a Floating IPs DNS pointer.  Contains an Action of type `change_dns_ptr`. )
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Floating IP.
   * @param body The `ip` attributes specifies for which IP address the record is set. For IPv4 addresses this must be the exact address of the Floating IP. For IPv6 addresses this must be a single address within the `/64` subnet of the Floating IP.  The `dns_ptr` attribute specifies the hostname used for the IP address. Must be a fully qualified domain name (FQDN) without trailing dot.  For IPv6 Floating IPs up to 100 entries can be created. 
   */
  def changeReverseDnsRecordsForFloatingIp(id: Long, body: DnsPtr)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ChangeReverseDnsRecordsForFloatingIpResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/floating_ips/${idPathParam}/actions/change_dns_ptr"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(body))
      .response(asJson[ChangeReverseDnsRecordsForFloatingIpResponse])

  /**
   * Create a Floating IP.  Provide the `server` attribute to assign the Floating IP to that server or provide a `home_location` to locate the Floating IP at. Note that the Floating IP can be assigned to a Server in any Location later on. For optimal routing it is advised to use the Floating IP in the same Location it was created in. 
   * 
   * Expected answers:
   *   code 201 : CreateFloatingIpResponse (Response for creating a Floating IP.  Contains the created IP. )
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param createFloatingIpRequest The `type` argument is required while `home_location` and `server` are mutually exclusive.
   */
  def createFloatingIp(createFloatingIpRequest: CreateFloatingIpRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], CreateFloatingIpResponse]] =
    val requestURL =
      uri"$baseUrl/floating_ips"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(createFloatingIpRequest))
      .response(asJson[CreateFloatingIpResponse])

  /**
   * Deletes a Floating IP.  If the IP is assigned to a resource it will be unassigned. 
   * 
   * Expected answers:
   *   code 204 :  (Floating IP deleted.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Floating IP.
   */
  def deleteFloatingIp(id: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], Unit]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/floating_ips/${idPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asString.mapWithMetadata(ResponseAs.deserializeRightWithError(_ => Right(()))))

  /**
   * Returns a specific Action for a Floating IP. 
   * 
   * Expected answers:
   *   code 200 : GetActionResponse (Response for getting an Action.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Floating IP.
   * @param actionId ID of the Action.
   */
  def getActionForFloatingIp(id: Long, actionId: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], GetActionResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val actionIdPathParam = PathSerializable.serialize("action_id", actionId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/floating_ips/${idPathParam}/actions/${actionIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /**
   * Returns a single Floating IP. 
   * 
   * Expected answers:
   *   code 200 : GetFloatingIpResponse (Response for getting a single Floating IP.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Floating IP.
   */
  def getFloatingIp(id: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], GetFloatingIpResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/floating_ips/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetFloatingIpResponse])

  /**
   * Returns a single Action. 
   * 
   * Expected answers:
   *   code 200 : GetActionResponse (Response for getting a single Action.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Action.
   */
  def getFloatingIpAction(id: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], GetActionResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/floating_ips/actions/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /**
   * Lists Actions for a Floating IP.  Use the provided URI parameters to modify the result. 
   * 
   * Expected answers:
   *   code 200 : ListActionsResponse (Response for listing Actions.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Floating IP.
   * @param sort Sort actions by field and direction. Can be used multiple times. For more information, see \"Sorting\". 
   * @param status Filter the actions by status. Can be used multiple times. The response will only contain actions matching the specified statuses. 
   * @param page Page number to return. For more information, see \"Pagination\".
   * @param perPage Maximum number of entries returned per page. For more information, see \"Pagination\".
   */
  def listActionsForFloatingIp(id: Long, sort: Seq[String], status: Seq[String], page: Option[Long] = scala.None, perPage: Option[Long] = scala.None)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ListActionsResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/floating_ips/${idPathParam}/actions"
        .addParams(FormSerializable.serialize("sort", sort, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("status", status, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("page", page, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("per_page", perPage, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /**
   * Lists multiple Actions.  Use the provided URI parameters to modify the result. 
   * 
   * Expected answers:
   *   code 200 : ListActionsResponse (Response for listing Actions.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id Filter the actions by ID. Can be used multiple times. The response will only contain actions matching the specified IDs. 
   * @param sort Sort actions by field and direction. Can be used multiple times. For more information, see \"Sorting\". 
   * @param status Filter the actions by status. Can be used multiple times. The response will only contain actions matching the specified statuses. 
   * @param page Page number to return. For more information, see \"Pagination\".
   * @param perPage Maximum number of entries returned per page. For more information, see \"Pagination\".
   */
  def listFloatingIpActions(id: Seq[Long], sort: Seq[String], status: Seq[String], page: Option[Long] = scala.None, perPage: Option[Long] = scala.None)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ListActionsResponse]] =
    val requestURL =
      uri"$baseUrl/floating_ips/actions"
        .addParams(FormSerializable.serialize("id", id, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("sort", sort, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("status", status, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("page", page, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("per_page", perPage, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /**
   * List multiple Floating IPs.  Use the provided URI parameters to modify the result. 
   * 
   * Expected answers:
   *   code 200 : ListFloatingIpsResponse (Response for listing Floating IPs.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param name Filter resources by their name. The response will only contain the resources matching exactly the specified name. 
   * @param labelSelector Filter resources by labels. The response will only contain resources matching the label selector. For more information, see \"Label Selector\". 
   * @param sort Sort resources by field and direction. Can be used multiple times. For more information, see \"Sorting\". 
   * @param page Page number to return. For more information, see \"Pagination\".
   * @param perPage Maximum number of entries returned per page. For more information, see \"Pagination\".
   */
  def listFloatingIps(name: Option[String] = scala.None, labelSelector: Option[String] = scala.None, sort: Seq[String], page: Option[Long] = scala.None, perPage: Option[Long] = scala.None)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ListFloatingIpsResponse]] =
    val requestURL =
      uri"$baseUrl/floating_ips"
        .addParams(FormSerializable.serialize("name", name, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("label_selector", labelSelector, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("sort", sort, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("page", page, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("per_page", perPage, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListFloatingIpsResponse])

  /**
   * Update a Floating IP. 
   * 
   * Expected answers:
   *   code 200 : ReplaceFloatingIpResponse (Response for updating a Floating IP.  Contains the updated Floating IP. )
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Floating IP.
   * @param replaceFloatingIpRequest 
   */
  def replaceFloatingIp(id: Long, replaceFloatingIpRequest: ReplaceFloatingIpRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ReplaceFloatingIpResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/floating_ips/${idPathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replaceFloatingIpRequest))
      .response(asJson[ReplaceFloatingIpResponse])

  /**
   * Unassigns a Floating IP.  Results in the IP being unreachable. Can be assigned to another resource again. 
   * 
   * Expected answers:
   *   code 201 : UnassignFloatingIpResponse (Response for unassigning a Floating IP.  Contains an Action of type `unassign_floating_ip`. )
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Floating IP.
   */
  def unassignFloatingIp(id: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], UnassignFloatingIpResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/floating_ips/${idPathParam}/actions/unassign"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[UnassignFloatingIpResponse])

end FloatingIps