/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.api

import hcloud.models.ChangeImageProtectionRequest
import hcloud.models.ChangeImageProtectionResponse
import hcloud.models.GetActionResponse
import hcloud.models.GetImageResponse
import hcloud.models.ListActionsResponse
import hcloud.models.ListImagesResponse
import hcloud.models.ReplaceImageRequest
import hcloud.models.ReplaceImageResponse
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object Images:
  def apply(
      baseUrl: String = "https://api.hetzner.cloud/v1"
  ): Images[hcloud.Authorization.NoAuthorization.type] =
    Images(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): Images[hcloud.Authorization.BasicAuth] =
    Images(baseUrl, hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): Images[hcloud.Authorization.ApiKey] =
    Images(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): Images[hcloud.Authorization.BearerToken] =
    Images(baseUrl, hcloud.Authorization.BearerToken(token))

case class Images[Auth <: hcloud.Authorization] private (
    baseUrl: String,
    authConfig: hcloud.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): Images[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): Images[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: Images[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): Images[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /** Changes the protection configuration of the Image. Can only be used on
    * snapshots.
    *
    * Expected answers: code 201 : ChangeImageProtectionResponse (The `action`
    * key contains the `change_protection` Action.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Image.
    * @param changeImageProtectionRequest
    */
  def changeImageProtection(
      id: Long,
      changeImageProtectionRequest: ChangeImageProtectionRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ChangeImageProtectionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/images/${idPathParam}/actions/change_protection"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeImageProtectionRequest))
      .response(asJson[ChangeImageProtectionResponse])

  /** Deletes an Image. Only Images of type `snapshot` and `backup` can be
    * deleted.
    *
    * Expected answers: code 204 : (Image deleted.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Image.
    */
  def deleteImage(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], Unit]] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/images/${idPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(_ => Right(()))
        )
      )

  /** Returns a specific Action for an Image.
    *
    * Expected answers: code 200 : GetActionResponse (The `action` key contains
    * the Image Action.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Image.
    * @param actionId
    *   ID of the Action.
    */
  def getActionForImage(id: Long, actionId: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetActionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val actionIdPathParam = PathSerializable.serialize(
      "action_id",
      actionId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/images/${idPathParam}/actions/${actionIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /** Returns a specific Image object.
    *
    * Expected answers: code 200 : GetImageResponse (The `image` key in the
    * reply contains an Image object with this structure.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Image.
    */
  def getImage(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], GetImageResponse]] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/images/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetImageResponse])

  /** Returns a specific Action object.
    *
    * Expected answers: code 200 : GetActionResponse (The `action` key in the
    * reply has this structure.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Action.
    */
  def getImageAction(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetActionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/images/actions/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /** Returns all Action objects for an Image. You can sort the results by using
    * the `sort` URI parameter, and filter them with the `status` parameter.
    *
    * Expected answers: code 200 : ListActionsResponse (The `actions` key
    * contains a list of Actions.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Image.
    * @param sort
    *   Sort actions by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param status
    *   Filter the actions by status. Can be used multiple times. The response
    *   will only contain actions matching the specified statuses.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listActionsForImage(
      id: Long,
      sort: Seq[String],
      status: Seq[String],
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListActionsResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/images/${idPathParam}/actions"
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /** Returns all Action objects. You can `sort` the results by using the sort
    * URI parameter, and filter them with the `status` and `id` parameter.
    *
    * Expected answers: code 200 : ListActionsResponse (The `actions` key
    * contains a list of Actions.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   Filter the actions by ID. Can be used multiple times. The response will
    *   only contain actions matching the specified IDs.
    * @param sort
    *   Sort actions by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param status
    *   Filter the actions by status. Can be used multiple times. The response
    *   will only contain actions matching the specified statuses.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listImageActions(
      id: Seq[Long],
      sort: Seq[String],
      status: Seq[String],
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListActionsResponse]
  ] =
    val requestURL =
      uri"$baseUrl/images/actions"
        .addParams(
          FormSerializable.serialize("id", id, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /** Returns all Image objects. You can select specific Image types only and
    * sort the results by using URI parameters.
    *
    * Expected answers: code 200 : ListImagesResponse (The `images` key in the
    * reply contains an array of Image objects with this structure.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param sort
    *   Sort resources by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param `type`
    *   Filter resources by type. Can be used multiple times. The response will
    *   only contain the resources with the specified type.
    * @param status
    *   Filter resources by status. Can be used multiple times. The response
    *   will only contain the resources with the specified status.
    * @param boundTo
    *   Can be used multiple times. Server ID linked to the Image. Only
    *   available for Images of type `backup`.
    * @param includeDeprecated
    *   Can be used multiple times.
    * @param name
    *   Filter resources by their name. The response will only contain the
    *   resources matching exactly the specified name.
    * @param labelSelector
    *   Filter resources by labels. The response will only contain resources
    *   matching the label selector. For more information, see \"Label
    *   Selector\".
    * @param architecture
    *   Filter resources by cpu architecture. The response will only contain the
    *   resources with the specified cpu architecture.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listImages(
      sort: Seq[String],
      `type`: Seq[String],
      status: Seq[String],
      boundTo: Seq[String],
      includeDeprecated: Option[Boolean] = scala.None,
      name: Option[String] = scala.None,
      labelSelector: Option[String] = scala.None,
      architecture: Option[String] = scala.None,
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListImagesResponse]
  ] =
    val requestURL =
      uri"$baseUrl/images"
        .addParams(
          FormSerializable.serialize(
            "sort",
            sort,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("type", `type`, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("bound_to", boundTo, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "include_deprecated",
            includeDeprecated,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("name", name, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "label_selector",
            labelSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "architecture",
            architecture,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListImagesResponse])

  /** Updates the Image. You may change the description, convert a Backup Image
    * to a Snapshot Image or change the Image labels. Only Images of type
    * `snapshot` and `backup` can be updated.
    *
    * Expected answers: code 200 : ReplaceImageResponse (The image key in the
    * reply contains the modified Image object.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Image.
    * @param replaceImageRequest
    */
  def replaceImage(id: Long, replaceImageRequest: ReplaceImageRequest)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ReplaceImageResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/images/${idPathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replaceImageRequest))
      .response(asJson[ReplaceImageResponse])

end Images
