/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.api

import hcloud.models.GetIsoResponse
import hcloud.models.ListIsosResponse
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object Isos:
  def apply(baseUrl: String = "https://api.hetzner.cloud/v1"): Isos[hcloud.Authorization.NoAuthorization.type] = Isos(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(baseUrl: String, username: String, password: String): Isos[hcloud.Authorization.BasicAuth] =
    Isos(baseUrl, hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(baseUrl: String, apiKey: String): Isos[hcloud.Authorization.ApiKey] =
    Isos(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(baseUrl: String, token: String): Isos[hcloud.Authorization.BearerToken] =
    Isos(baseUrl, hcloud.Authorization.BearerToken(token))

case class Isos[Auth <: hcloud.Authorization] private (baseUrl: String, authConfig: hcloud.Authorization):
  def withBasicAuth(username: String, password: String): Isos[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): Isos[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: Isos[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(token: String): Isos[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /**
   * Returns a specific ISO object. 
   * 
   * Expected answers:
   *   code 200 : GetIsoResponse (The `iso` key in the reply contains an array of ISO objects with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the ISO.
   */
  def getIso(id: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], GetIsoResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/isos/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetIsoResponse])

  /**
   * Returns all available ISO objects. 
   * 
   * Expected answers:
   *   code 200 : ListIsosResponse (The `isos` key in the reply contains an array of iso objects with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param name Filter resources by their name. The response will only contain the resources matching exactly the specified name. 
   * @param architecture Filter resources by cpu architecture. The response will only contain the resources with the specified cpu architecture. 
   * @param includeArchitectureWildcard Include Images with wildcard architecture (architecture is null). Works only if architecture filter is specified.
   * @param page Page number to return. For more information, see \"Pagination\".
   * @param perPage Maximum number of entries returned per page. For more information, see \"Pagination\".
   */
  def listIsos(name: Option[String] = scala.None, architecture: Option[String] = scala.None, includeArchitectureWildcard: Option[Boolean] = scala.None, page: Option[Long] = scala.None, perPage: Option[Long] = scala.None)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ListIsosResponse]] =
    val requestURL =
      uri"$baseUrl/isos"
        .addParams(FormSerializable.serialize("name", name, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("architecture", architecture, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("include_architecture_wildcard", includeArchitectureWildcard, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("page", page, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("per_page", perPage, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListIsosResponse])

end Isos