/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.api

import hcloud.models.GetLoadBalancerTypeResponse
import hcloud.models.ListLoadBalancerTypesResponse
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object LoadBalancerTypes:
  def apply(
      baseUrl: String = "https://api.hetzner.cloud/v1"
  ): LoadBalancerTypes[hcloud.Authorization.NoAuthorization.type] =
    LoadBalancerTypes(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): LoadBalancerTypes[hcloud.Authorization.BasicAuth] =
    LoadBalancerTypes(
      baseUrl,
      hcloud.Authorization.BasicAuth(username, password)
    )

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): LoadBalancerTypes[hcloud.Authorization.ApiKey] =
    LoadBalancerTypes(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): LoadBalancerTypes[hcloud.Authorization.BearerToken] =
    LoadBalancerTypes(baseUrl, hcloud.Authorization.BearerToken(token))

case class LoadBalancerTypes[Auth <: hcloud.Authorization] private (
    baseUrl: String,
    authConfig: hcloud.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): LoadBalancerTypes[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(
      apiKey: String
  ): LoadBalancerTypes[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: LoadBalancerTypes[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): LoadBalancerTypes[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /** Gets a specific Load Balancer type object.
    *
    * Expected answers: code 200 : GetLoadBalancerTypeResponse (The
    * `load_balancer_type` key in the reply contains a Load Balancer type object
    * with this structure.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Load Balancer Type.
    */
  def getLoadBalancerType(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetLoadBalancerTypeResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/load_balancer_types/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetLoadBalancerTypeResponse])

  /** Gets all Load Balancer type objects.
    *
    * Expected answers: code 200 : ListLoadBalancerTypesResponse (The
    * `load_balancer_types` key in the reply contains an array of Load Balancer
    * type objects with this structure.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param name
    *   Filter resources by their name. The response will only contain the
    *   resources matching exactly the specified name.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listLoadBalancerTypes(
      name: Option[String] = scala.None,
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListLoadBalancerTypesResponse]
  ] =
    val requestURL =
      uri"$baseUrl/load_balancer_types"
        .addParams(
          FormSerializable
            .serialize("name", name, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListLoadBalancerTypesResponse])

end LoadBalancerTypes
