/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.api

import hcloud.models.AddRouteToNetworkResponse
import hcloud.models.AddSubnetToNetworkResponse
import hcloud.models.ChangeIpRangeOfNetworkRequest
import hcloud.models.ChangeIpRangeOfNetworkResponse
import hcloud.models.ChangeNetworkProtectionRequest
import hcloud.models.ChangeNetworkProtectionResponse
import hcloud.models.CreateNetworkRequest
import hcloud.models.CreateNetworkResponse
import hcloud.models.DeleteRouteFromNetworkResponse
import hcloud.models.DeleteSubnetFromNetworkRequest
import hcloud.models.DeleteSubnetFromNetworkResponse
import hcloud.models.GetActionResponse
import hcloud.models.GetNetworkResponse
import hcloud.models.ListActionsResponse
import hcloud.models.ListNetworksResponse
import hcloud.models.ReplaceNetworkRequest
import hcloud.models.ReplaceNetworkResponse
import hcloud.models.Route
import hcloud.models.Subnet
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object Networks:
  def apply(
      baseUrl: String = "https://api.hetzner.cloud/v1"
  ): Networks[hcloud.Authorization.NoAuthorization.type] =
    Networks(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): Networks[hcloud.Authorization.BasicAuth] =
    Networks(baseUrl, hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): Networks[hcloud.Authorization.ApiKey] =
    Networks(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): Networks[hcloud.Authorization.BearerToken] =
    Networks(baseUrl, hcloud.Authorization.BearerToken(token))

case class Networks[Auth <: hcloud.Authorization] private (
    baseUrl: String,
    authConfig: hcloud.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): Networks[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): Networks[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: Networks[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): Networks[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /** Adds a route entry to a Network. If a change is currently being performed
    * on this Network, a error response with code `conflict` will be returned.
    *
    * Expected answers: code 201 : AddRouteToNetworkResponse (Response for
    * adding a route to a Network. The `action` key contains an Action with
    * command `add_route`. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Network.
    * @param body
    */
  def addRouteToNetwork(id: Long, body: Route)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], AddRouteToNetworkResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/networks/${idPathParam}/actions/add_route"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(body))
      .response(asJson[AddRouteToNetworkResponse])

  /** Adds a new subnet to the Network. If the subnet `ip_range` is not
    * provided, the first available `/24` IP range will be used. If a change is
    * currently being performed on this Network, a error response with code
    * `conflict` will be returned.
    *
    * Expected answers: code 201 : AddSubnetToNetworkResponse (Response for
    * adding a subnet to a Network. The `action` key contains an Action with
    * command `add_subnet`. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Network.
    * @param body
    */
  def addSubnetToNetwork(id: Long, body: Subnet)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], AddSubnetToNetworkResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/networks/${idPathParam}/actions/add_subnet"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(body))
      .response(asJson[AddSubnetToNetworkResponse])

  /** Changes the IP range of a Network. The following restrictions apply to
    * changing the IP range: - IP ranges can only be extended and never shrunk. -
    * IPs can only be added to the end of the existing range, therefore only the
    * netmask is allowed to be changed. To update the routes on the connected
    * Servers, they need to be rebooted or the routes to be updated manually.
    * For example if the Network has a range of `10.0.0.0/16` to extend it the
    * new range has to start with the IP `10.0.0.0` as well. The netmask `/16`
    * can be changed to a smaller one then `16` therefore increasing the IP
    * range. A valid entry would be `10.0.0.0/15`, `10.0.0.0/14` or
    * `10.0.0.0/13` and so on. If a change is currently being performed on this
    * Network, a error response with code `conflict` will be returned.
    *
    * Expected answers: code 201 : ChangeIpRangeOfNetworkResponse (Response for
    * changing the Networks IP range. The `action` key contains an Action with
    * command `change_ip_range`. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Network.
    * @param changeIpRangeOfNetworkRequest
    */
  def changeIpRangeOfNetwork(
      id: Long,
      changeIpRangeOfNetworkRequest: ChangeIpRangeOfNetworkRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ChangeIpRangeOfNetworkResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/networks/${idPathParam}/actions/change_ip_range"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeIpRangeOfNetworkRequest))
      .response(asJson[ChangeIpRangeOfNetworkResponse])

  /** Changes the protection settings of a Network. If a change is currently
    * being performed on this Network, a error response with code `conflict`
    * will be returned.
    *
    * Expected answers: code 201 : ChangeNetworkProtectionResponse (Response for
    * changing the Networks protection. The `action` key contains an Action with
    * command `change_protection`. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Network.
    * @param changeNetworkProtectionRequest
    */
  def changeNetworkProtection(
      id: Long,
      changeNetworkProtectionRequest: ChangeNetworkProtectionRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ChangeNetworkProtectionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/networks/${idPathParam}/actions/change_protection"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeNetworkProtectionRequest))
      .response(asJson[ChangeNetworkProtectionResponse])

  /** Creates a Network. The provided `ip_range` can only be extended later on,
    * but not reduced. Subnets can be added now or later on using the add subnet
    * action. If you do not specify an `ip_range` for the subnet the first
    * available /24 range will be used. Routes can be added now or later by
    * using the add route action.
    *
    * Expected answers: code 201 : CreateNetworkResponse (Response for creating
    * a Network. Contains the newly created Network. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param createNetworkRequest
    */
  def createNetwork(createNetworkRequest: CreateNetworkRequest)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], CreateNetworkResponse]
  ] =
    val requestURL =
      uri"$baseUrl/networks"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(createNetworkRequest))
      .response(asJson[CreateNetworkResponse])

  /** Deletes a Network. Attached resources will be detached automatically.
    *
    * Expected answers: code 204 : (Response for deleting a Network.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Network.
    */
  def deleteNetwork(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], Unit]] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/networks/${idPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(_ => Right(()))
        )
      )

  /** Delete a route entry from a Network. If a change is currently being
    * performed on this Network, a error response with code `conflict` will be
    * returned.
    *
    * Expected answers: code 201 : DeleteRouteFromNetworkResponse (Response for
    * deleting a route from a Network. The `action` key contains an Action with
    * command `delete_route`. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Network.
    * @param body
    */
  def deleteRouteFromNetwork(id: Long, body: Route)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], DeleteRouteFromNetworkResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/networks/${idPathParam}/actions/delete_route"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(body))
      .response(asJson[DeleteRouteFromNetworkResponse])

  /** Deletes a single subnet entry from a Network. Subnets containing attached
    * resources can not be deleted, they must be detached beforehand. If a
    * change is currently being performed on this Network, a error response with
    * code `conflict` will be returned.
    *
    * Expected answers: code 201 : DeleteSubnetFromNetworkResponse (Response for
    * deleting a subnet from a Network. The `action` key contains an Action with
    * command `delete_subnet`. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Network.
    * @param deleteSubnetFromNetworkRequest
    */
  def deleteSubnetFromNetwork(
      id: Long,
      deleteSubnetFromNetworkRequest: DeleteSubnetFromNetworkRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], DeleteSubnetFromNetworkResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/networks/${idPathParam}/actions/delete_subnet"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(deleteSubnetFromNetworkRequest))
      .response(asJson[DeleteSubnetFromNetworkResponse])

  /** Returns a specific Action for a Network.
    *
    * Expected answers: code 200 : GetActionResponse (Response for getting an
    * Action.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Network.
    * @param actionId
    *   ID of the Action.
    */
  def getActionForNetwork(id: Long, actionId: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetActionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val actionIdPathParam = PathSerializable.serialize(
      "action_id",
      actionId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/networks/${idPathParam}/actions/${actionIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /** Get a specific Network.
    *
    * Expected answers: code 200 : GetNetworkResponse (The `network` key
    * contains the network.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Network.
    */
  def getNetwork(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetNetworkResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/networks/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetNetworkResponse])

  /** Returns a single Action.
    *
    * Expected answers: code 200 : GetActionResponse (Response for getting a
    * single Action.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Action.
    */
  def getNetworkAction(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetActionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/networks/actions/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /** Lists Actions for a Network. Use the provided URI parameters to modify the
    * result.
    *
    * Expected answers: code 200 : ListActionsResponse (Response for listing
    * Actions.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Network.
    * @param sort
    *   Sort actions by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param status
    *   Filter the actions by status. Can be used multiple times. The response
    *   will only contain actions matching the specified statuses.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listActionsForNetwork(
      id: Long,
      sort: Seq[String],
      status: Seq[String],
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListActionsResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/networks/${idPathParam}/actions"
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /** Lists multiple Actions. Use the provided URI parameters to modify the
    * result.
    *
    * Expected answers: code 200 : ListActionsResponse (Response for listing
    * Actions.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   Filter the actions by ID. Can be used multiple times. The response will
    *   only contain actions matching the specified IDs.
    * @param sort
    *   Sort actions by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param status
    *   Filter the actions by status. Can be used multiple times. The response
    *   will only contain actions matching the specified statuses.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listNetworkActions(
      id: Seq[Long],
      sort: Seq[String],
      status: Seq[String],
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListActionsResponse]
  ] =
    val requestURL =
      uri"$baseUrl/networks/actions"
        .addParams(
          FormSerializable.serialize("id", id, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /** List multiple Networks. Use the provided URI parameters to modify the
    * result.
    *
    * Expected answers: code 200 : ListNetworksResponse (Response for listing
    * Networks.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param sort
    *   Sort resources by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param name
    *   Filter resources by their name. The response will only contain the
    *   resources matching exactly the specified name.
    * @param labelSelector
    *   Filter resources by labels. The response will only contain resources
    *   matching the label selector. For more information, see \"Label
    *   Selector\".
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listNetworks(
      sort: Seq[String],
      name: Option[String] = scala.None,
      labelSelector: Option[String] = scala.None,
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListNetworksResponse]
  ] =
    val requestURL =
      uri"$baseUrl/networks"
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("name", name, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "label_selector",
            labelSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListNetworksResponse])

  /** Update a Network. If a change is currently being performed on this
    * Network, a error response with code `conflict` will be returned.
    *
    * Expected answers: code 200 : ReplaceNetworkResponse (Response for updating
    * a Network. Contains the updated Network. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Network.
    * @param replaceNetworkRequest
    */
  def replaceNetwork(id: Long, replaceNetworkRequest: ReplaceNetworkRequest)(
      using Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ReplaceNetworkResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/networks/${idPathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replaceNetworkRequest))
      .response(asJson[ReplaceNetworkResponse])

end Networks
