/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.api

import hcloud.models.CreatePlacementgroupRequest
import hcloud.models.CreatePlacementgroupResponse
import hcloud.models.GetPlacementgroupResponse
import hcloud.models.ListPlacementGroupsResponse
import hcloud.models.ReplacePlacementgroupRequest
import hcloud.models.ReplacePlacementgroupResponse
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object PlacementGroups:
  def apply(baseUrl: String = "https://api.hetzner.cloud/v1"): PlacementGroups[hcloud.Authorization.NoAuthorization.type] = PlacementGroups(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(baseUrl: String, username: String, password: String): PlacementGroups[hcloud.Authorization.BasicAuth] =
    PlacementGroups(baseUrl, hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(baseUrl: String, apiKey: String): PlacementGroups[hcloud.Authorization.ApiKey] =
    PlacementGroups(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(baseUrl: String, token: String): PlacementGroups[hcloud.Authorization.BearerToken] =
    PlacementGroups(baseUrl, hcloud.Authorization.BearerToken(token))

case class PlacementGroups[Auth <: hcloud.Authorization] private (baseUrl: String, authConfig: hcloud.Authorization):
  def withBasicAuth(username: String, password: String): PlacementGroups[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): PlacementGroups[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: PlacementGroups[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(token: String): PlacementGroups[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /**
   * Creates a new Placement Group. 
   * 
   * Expected answers:
   *   code 201 : CreatePlacementgroupResponse (The `PlacementGroup` key contains the Placement Group that was just created.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param createPlacementgroupRequest 
   */
  def createPlacementgroup(createPlacementgroupRequest: CreatePlacementgroupRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], CreatePlacementgroupResponse]] =
    val requestURL =
      uri"$baseUrl/placement_groups"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(createPlacementgroupRequest))
      .response(asJson[CreatePlacementgroupResponse])

  /**
   * Deletes a Placement Group. 
   * 
   * Expected answers:
   *   code 204 :  (Placement Group deleted.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Placement Group.
   */
  def deletePlacementgroup(id: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], Unit]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/placement_groups/${idPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asString.mapWithMetadata(ResponseAs.deserializeRightWithError(_ => Right(()))))

  /**
   * Gets a specific Placement Group object. 
   * 
   * Expected answers:
   *   code 200 : GetPlacementgroupResponse (The `placement_group` key contains a Placement Group object.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Placement Group.
   */
  def getPlacementgroup(id: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], GetPlacementgroupResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/placement_groups/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetPlacementgroupResponse])

  /**
   * Returns all Placement Group objects. 
   * 
   * Expected answers:
   *   code 200 : ListPlacementGroupsResponse (The `placement_groups` key contains an array of Placement Group objects.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param sort Sort resources by field and direction. Can be used multiple times. For more information, see \"Sorting\". 
   * @param name Filter resources by their name. The response will only contain the resources matching exactly the specified name. 
   * @param labelSelector Filter resources by labels. The response will only contain resources matching the label selector. For more information, see \"Label Selector\". 
   * @param `type` Filter resources by type. Can be used multiple times. The response will only contain the resources with the specified type. 
   * @param page Page number to return. For more information, see \"Pagination\".
   * @param perPage Maximum number of entries returned per page. For more information, see \"Pagination\".
   */
  def listPlacementGroups(sort: Seq[String], name: Option[String] = scala.None, labelSelector: Option[String] = scala.None, `type`: Seq[String], page: Option[Long] = scala.None, perPage: Option[Long] = scala.None)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ListPlacementGroupsResponse]] =
    val requestURL =
      uri"$baseUrl/placement_groups"
        .addParams(FormSerializable.serialize("sort", sort, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("name", name, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("label_selector", labelSelector, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("type", `type`, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("page", page, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("per_page", perPage, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListPlacementGroupsResponse])

  /**
   * Updates the Placement Group properties.  Note: if the Placement Group object changes during the request, the response will be a “conflict” error. 
   * 
   * Expected answers:
   *   code 200 : ReplacePlacementgroupResponse (The `certificate` key contains the Placement Group that was just updated.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Placement Group.
   * @param replacePlacementgroupRequest 
   */
  def replacePlacementgroup(id: Long, replacePlacementgroupRequest: ReplacePlacementgroupRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ReplacePlacementgroupResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/placement_groups/${idPathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replacePlacementgroupRequest))
      .response(asJson[ReplacePlacementgroupResponse])

end PlacementGroups