/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.api

import hcloud.models.AssignPrimaryIpToResourceRequest
import hcloud.models.AssignPrimaryIpToResourceResponse
import hcloud.models.ChangePrimaryIpProtectionResponse
import hcloud.models.ChangeReverseDnsRecordsForPrimaryIpResponse
import hcloud.models.CreatePrimaryIpRequest
import hcloud.models.CreatePrimaryIpResponse
import hcloud.models.DnsPtr
import hcloud.models.GetActionResponse
import hcloud.models.GetPrimaryIpResponse
import hcloud.models.ListActionsResponse
import hcloud.models.ListPrimaryIpsResponse
import hcloud.models.Protection
import hcloud.models.ReplacePrimaryIpRequest
import hcloud.models.ReplacePrimaryIpResponse
import hcloud.models.UnassignPrimaryIpFromResourceResponse
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object PrimaryIps:
  def apply(
      baseUrl: String = "https://api.hetzner.cloud/v1"
  ): PrimaryIps[hcloud.Authorization.NoAuthorization.type] =
    PrimaryIps(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): PrimaryIps[hcloud.Authorization.BasicAuth] =
    PrimaryIps(baseUrl, hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): PrimaryIps[hcloud.Authorization.ApiKey] =
    PrimaryIps(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): PrimaryIps[hcloud.Authorization.BearerToken] =
    PrimaryIps(baseUrl, hcloud.Authorization.BearerToken(token))

case class PrimaryIps[Auth <: hcloud.Authorization] private (
    baseUrl: String,
    authConfig: hcloud.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): PrimaryIps[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): PrimaryIps[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: PrimaryIps[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): PrimaryIps[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /** Assign a Primary IP to a resource. A Server can only have one Primary IP
    * of type `ipv4` and one of type `ipv6` assigned. If you need more IPs use
    * Floating IPs. A Server must be powered off (status `off`) in order for
    * this operation to succeed. #### Error Codes specific to this Call | Code |
    * Description | |------------------------------ |--------------------------------------------------------------------------------- | |
    * `server_not_stopped` | The Server is running, but needs to be powered off | |
    * `primary_ip_already_assigned` | Primary IP is already assigned to a
    * different Server | | `server_has_ipv4` | The Server already has an IPv4
    * address | | `server_has_ipv6` | The Server already has an IPv6 address |
    *
    * Expected answers: code 201 : AssignPrimaryIpToResourceResponse (Response
    * for assigning a Primary IP. Contains an Action of type
    * `assign_primary_ip`. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Primary IP.
    * @param assignPrimaryIpToResourceRequest
    */
  def assignPrimaryIpToResource(
      id: Long,
      assignPrimaryIpToResourceRequest: AssignPrimaryIpToResourceRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], AssignPrimaryIpToResourceResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/primary_ips/${idPathParam}/actions/assign"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(assignPrimaryIpToResourceRequest))
      .response(asJson[AssignPrimaryIpToResourceResponse])

  /** Changes the protection configuration of a Primary IP. A Primary IPs
    * deletion protection can only be enabled if its `auto_delete` property is
    * set to `false`.
    *
    * Expected answers: code 201 : ChangePrimaryIpProtectionResponse (Response
    * for changing a Primary IPs protection settings. Contains an Action of type
    * `change_protection`. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Primary IP.
    * @param body
    */
  def changePrimaryIpProtection(id: Long, body: Protection)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ChangePrimaryIpProtectionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/primary_ips/${idPathParam}/actions/change_protection"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(body))
      .response(asJson[ChangePrimaryIpProtectionResponse])

  /** Change the reverse DNS records for this Primary IP. Allows to modify the
    * PTR records set for the IP address.
    *
    * Expected answers: code 201 : ChangeReverseDnsRecordsForPrimaryIpResponse
    * (Response for changing a Primary IPs DNS pointer. Contains an Action of
    * type `change_dns_ptr`. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Primary IP.
    * @param body
    *   The `ip` attributes specifies for which IP address the record is set.
    *   For IPv4 addresses this must be the exact address of the Primary IP. For
    *   IPv6 addresses this must be a single address within the `/64` subnet of
    *   the Primary IP. The `dns_ptr` attribute specifies the hostname used for
    *   the IP address. Must be a fully qualified domain name (FQDN) without
    *   trailing dot. For IPv6 Primary IPs up to 100 entries can be created.
    */
  def changeReverseDnsRecordsForPrimaryIp(id: Long, body: DnsPtr)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[
    String
  ], ChangeReverseDnsRecordsForPrimaryIpResponse]] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/primary_ips/${idPathParam}/actions/change_dns_ptr"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(body))
      .response(asJson[ChangeReverseDnsRecordsForPrimaryIpResponse])

  /** Create a new Primary IP. Can optionally be assigned to a resource by
    * providing an `assignee_id` and `assignee_type`. If not assigned to a
    * resource the `datacenter` key needs to be provided. This can be either the
    * ID or the name of the Data Center this Primary IP shall be created in. A
    * Primary IP can only be assigned to resource in the same Data Center later
    * on. #### Call specific error codes | Code | Description | |------------------------------ |------------------------------------------------------------------------- | |
    * `server_not_stopped` | The specified Server is running, but needs to be
    * powered off | | `server_has_ipv4` | The Server already has an ipv4 address | |
    * `server_has_ipv6` | The Server already has an ipv6 address |
    *
    * Expected answers: code 201 : CreatePrimaryIpResponse (Response for
    * creating a Primary IP. Contains the newly created Primary IP. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param createPrimaryIpRequest
    *   Request Body for creating a new Primary IP. The `datacenter` and
    *   `assignee_id`/`assignee_type` attributes are mutually exclusive.
    */
  def createPrimaryIp(createPrimaryIpRequest: CreatePrimaryIpRequest)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], CreatePrimaryIpResponse]
  ] =
    val requestURL =
      uri"$baseUrl/primary_ips"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(createPrimaryIpRequest))
      .response(asJson[CreatePrimaryIpResponse])

  /** Deletes a Primary IP. If assigned to a Server the Primary IP will be
    * unassigned automatically. The Server must be powered off (status `off`) in
    * order for this operation to succeed.
    *
    * Expected answers: code 204 : (Primary IP deletion succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Primary IP.
    */
  def deletePrimaryIp(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], Unit]] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/primary_ips/${idPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(_ => Right(()))
        )
      )

  /** Returns a Primary IP.
    *
    * Expected answers: code 200 : GetPrimaryIpResponse (The `primary_ip` key
    * contains the Primary IP.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Primary IP.
    */
  def getPrimaryIp(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetPrimaryIpResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/primary_ips/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetPrimaryIpResponse])

  /** Returns a single Action.
    *
    * Expected answers: code 200 : GetActionResponse (Response for getting a
    * single Action.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Action.
    */
  def getPrimaryIpAction(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetActionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/primary_ips/actions/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /** Lists multiple Actions. Use the provided URI parameters to modify the
    * result.
    *
    * Expected answers: code 200 : ListActionsResponse (Response for listing
    * Actions.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   Filter the actions by ID. Can be used multiple times. The response will
    *   only contain actions matching the specified IDs.
    * @param sort
    *   Sort actions by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param status
    *   Filter the actions by status. Can be used multiple times. The response
    *   will only contain actions matching the specified statuses.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listPrimaryIpActions(
      id: Seq[Long],
      sort: Seq[String],
      status: Seq[String],
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListActionsResponse]
  ] =
    val requestURL =
      uri"$baseUrl/primary_ips/actions"
        .addParams(
          FormSerializable.serialize("id", id, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /** List multiple Primary IPs. Use the provided URI parameters to modify the
    * result.
    *
    * Expected answers: code 200 : ListPrimaryIpsResponse (Response for listing
    * Primary IPs.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param name
    *   Filter resources by their name. The response will only contain the
    *   resources matching exactly the specified name.
    * @param labelSelector
    *   Filter resources by labels. The response will only contain resources
    *   matching the label selector. For more information, see \"Label
    *   Selector\".
    * @param ip
    *   Filter results by IP address.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    * @param sort
    *   Sort resources by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    */
  def listPrimaryIps(
      name: Option[String] = scala.None,
      labelSelector: Option[String] = scala.None,
      ip: Option[String] = scala.None,
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None,
      sort: Seq[String]
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListPrimaryIpsResponse]
  ] =
    val requestURL =
      uri"$baseUrl/primary_ips"
        .addParams(
          FormSerializable
            .serialize("name", name, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "label_selector",
            labelSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize("ip", ip, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListPrimaryIpsResponse])

  /** Update a Primary IP. If another change is concurrently performed on this
    * Primary IP, a error response with code `conflict` will be returned.
    *
    * Expected answers: code 200 : ReplacePrimaryIpResponse (The `primary_ip`
    * key contains the updated Primary IP.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Primary IP.
    * @param replacePrimaryIpRequest
    */
  def replacePrimaryIp(
      id: Long,
      replacePrimaryIpRequest: ReplacePrimaryIpRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ReplacePrimaryIpResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/primary_ips/${idPathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replacePrimaryIpRequest))
      .response(asJson[ReplacePrimaryIpResponse])

  /** Unassign a Primary IP from a resource. A Server must be powered off
    * (status `off`) in order for this operation to succeed. A Server requires
    * at least one network interface (public or private) to be powered on. ####
    * Error Codes specific to this Call | Code | Description | |---------------------------------- |-------------------------------------------------------------- | |
    * `server_not_stopped` | The Server is running, but needs to be powered off | |
    * `server_is_load_balancer_target` | The Server IPv4 address is a
    * loadbalancer target |
    *
    * Expected answers: code 201 : UnassignPrimaryIpFromResourceResponse
    * (Response for unassigning a Primary IP. Contains an Action of type
    * `unassign_primary_ip`. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Primary IP.
    */
  def unassignPrimaryIpFromResource(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], UnassignPrimaryIpFromResourceResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/primary_ips/${idPathParam}/actions/unassign"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[UnassignPrimaryIpFromResourceResponse])

end PrimaryIps
