/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.api

import hcloud.models.CreateSshKeyRequest
import hcloud.models.CreateSshKeyResponse
import hcloud.models.GetSshKeyResponse
import hcloud.models.ListSshKeysResponse
import hcloud.models.ReplaceSshKeyRequest
import hcloud.models.ReplaceSshKeyResponse
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object SshKeys:
  def apply(
      baseUrl: String = "https://api.hetzner.cloud/v1"
  ): SshKeys[hcloud.Authorization.NoAuthorization.type] =
    SshKeys(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): SshKeys[hcloud.Authorization.BasicAuth] =
    SshKeys(baseUrl, hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): SshKeys[hcloud.Authorization.ApiKey] =
    SshKeys(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): SshKeys[hcloud.Authorization.BearerToken] =
    SshKeys(baseUrl, hcloud.Authorization.BearerToken(token))

case class SshKeys[Auth <: hcloud.Authorization] private (
    baseUrl: String,
    authConfig: hcloud.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): SshKeys[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): SshKeys[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: SshKeys[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): SshKeys[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /** Creates a new SSH key with the given `name` and `public_key`. Once an SSH
    * key is created, it can be used in other calls such as creating Servers.
    *
    * Expected answers: code 201 : CreateSshKeyResponse (The `ssh_key` key in
    * the reply contains the object that was just created.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param createSshKeyRequest
    */
  def createSshKey(createSshKeyRequest: CreateSshKeyRequest)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], CreateSshKeyResponse]
  ] =
    val requestURL =
      uri"$baseUrl/ssh_keys"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(createSshKeyRequest))
      .response(asJson[CreateSshKeyResponse])

  /** Deletes an SSH key. It cannot be used anymore.
    *
    * Expected answers: code 204 : (SSH key deleted.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the SSH Key.
    */
  def deleteSshKey(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], Unit]] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/ssh_keys/${idPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(_ => Right(()))
        )
      )

  /** Returns a specific SSH key object.
    *
    * Expected answers: code 200 : GetSshKeyResponse (The `ssh_key` key in the
    * reply contains an SSH key object with this structure.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the SSH Key.
    */
  def getSshKey(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetSshKeyResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/ssh_keys/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetSshKeyResponse])

  /** Returns all SSH key objects.
    *
    * Expected answers: code 200 : ListSshKeysResponse (The `ssh_keys` key in
    * the reply contains an array of SSH key objects with this structure.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param sort
    *   Sort resources by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param name
    *   Filter resources by their name. The response will only contain the
    *   resources matching exactly the specified name.
    * @param fingerprint
    *   Can be used to filter SSH keys by their fingerprint. The response will
    *   only contain the SSH key matching the specified fingerprint.
    * @param labelSelector
    *   Filter resources by labels. The response will only contain resources
    *   matching the label selector. For more information, see \"Label
    *   Selector\".
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listSshKeys(
      sort: Seq[String],
      name: Option[String] = scala.None,
      fingerprint: Option[String] = scala.None,
      labelSelector: Option[String] = scala.None,
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListSshKeysResponse]
  ] =
    val requestURL =
      uri"$baseUrl/ssh_keys"
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("name", name, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "fingerprint",
            fingerprint,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable.serialize(
            "label_selector",
            labelSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListSshKeysResponse])

  /** Updates an SSH key. You can update an SSH key name and an SSH key labels.
    *
    * Expected answers: code 200 : ReplaceSshKeyResponse (The `ssh_key` key in
    * the reply contains the modified SSH key object with the new description.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the SSH Key.
    * @param replaceSshKeyRequest
    */
  def replaceSshKey(id: Long, replaceSshKeyRequest: ReplaceSshKeyRequest)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ReplaceSshKeyResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/ssh_keys/${idPathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replaceSshKeyRequest))
      .response(asJson[ReplaceSshKeyResponse])

end SshKeys
