/**
 * Hetzner Cloud API
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hcloud.api

import hcloud.models.ChangeHomeDirectoryRequest
import hcloud.models.ChangeHomeDirectoryResponse
import hcloud.models.ChangeProtectionRequest
import hcloud.models.ChangeProtectionResponse
import hcloud.models.ChangeTypeRequest
import hcloud.models.ChangeTypeResponse
import hcloud.models.CreateSnapshotRequest
import hcloud.models.CreateSnapshotResponse
import hcloud.models.CreateStorageBoxRequest
import hcloud.models.CreateStorageBoxResponse
import hcloud.models.CreateSubaccountRequest
import hcloud.models.CreateSubaccountResponse
import hcloud.models.DeleteSnapshotResponse
import hcloud.models.DeleteStorageBoxResponse
import hcloud.models.DeleteSubaccountResponse
import hcloud.models.DisableSnapshotPlanResponse
import hcloud.models.EnableSnapshotPlanRequest
import hcloud.models.EnableSnapshotPlanResponse
import hcloud.models.GetActionResponse
import hcloud.models.GetSnapshotResponse
import hcloud.models.GetStorageBoxResponse
import hcloud.models.GetSubaccountResponse
import hcloud.models.ListActionsResponse
import hcloud.models.ListFoldersOfStorageBoxResponse
import hcloud.models.ListSnapshotsResponse
import hcloud.models.ListStorageBoxesResponse
import hcloud.models.ListSubaccountsResponse
import hcloud.models.ReplaceSnapshotRequest
import hcloud.models.ReplaceSnapshotResponse
import hcloud.models.ReplaceStorageBoxRequest
import hcloud.models.ReplaceStorageBoxResponse
import hcloud.models.ReplaceSubaccountRequest
import hcloud.models.ReplaceSubaccountResponse
import hcloud.models.ResetPasswordRequest
import hcloud.models.ResetPasswordResponse
import hcloud.models.RollbackSnapshotRequest
import hcloud.models.RollbackSnapshotResponse
import hcloud.models.UpdateAccessSettingsRequest
import hcloud.models.UpdateAccessSettingsResponse
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object StorageBoxes:
  def apply(baseUrl: String = "https://api.hetzner.cloud/v1"): StorageBoxes[hcloud.Authorization.NoAuthorization.type] = StorageBoxes(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(baseUrl: String, username: String, password: String): StorageBoxes[hcloud.Authorization.BasicAuth] =
    StorageBoxes(baseUrl, hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(baseUrl: String, apiKey: String): StorageBoxes[hcloud.Authorization.ApiKey] =
    StorageBoxes(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(baseUrl: String, token: String): StorageBoxes[hcloud.Authorization.BearerToken] =
    StorageBoxes(baseUrl, hcloud.Authorization.BearerToken(token))

case class StorageBoxes[Auth <: hcloud.Authorization] private (baseUrl: String, authConfig: hcloud.Authorization):
  def withBasicAuth(username: String, password: String): StorageBoxes[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): StorageBoxes[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: StorageBoxes[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(token: String): StorageBoxes[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /**
   * Change the home directory of a Storage Box Subaccount. 
   * 
   * Expected answers:
   *   code 201 : ChangeHomeDirectoryResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param subaccountId ID of the Storage Box Subaccount.
   * @param changeHomeDirectoryRequest 
   */
  def changeHomeDirectory(id: Long, subaccountId: Long, changeHomeDirectoryRequest: ChangeHomeDirectoryRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ChangeHomeDirectoryResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val subaccountIdPathParam = PathSerializable.serialize("subaccount_id", subaccountId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/subaccounts/${subaccountIdPathParam}/actions/change_home_directory"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeHomeDirectoryRequest))
      .response(asJson[ChangeHomeDirectoryResponse])

  /**
   * Changes the protection configuration of a Storage Box. 
   * 
   * Expected answers:
   *   code 201 : ChangeProtectionResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param changeProtectionRequest 
   */
  def changeProtection(id: Long, changeProtectionRequest: ChangeProtectionRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ChangeProtectionResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/actions/change_protection"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeProtectionRequest))
      .response(asJson[ChangeProtectionResponse])

  /**
   * Changes the type of a Storage Box.  Upgrades or downgrades a Storage Box to another Storage Box Type.  It is not possible to downgrade to a Storage Box Type that offers less disk space than you are currently using. 
   * 
   * Expected answers:
   *   code 201 : ChangeTypeResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param changeTypeRequest 
   */
  def changeType(id: Long, changeTypeRequest: ChangeTypeRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ChangeTypeResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/actions/change_type"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeTypeRequest))
      .response(asJson[ChangeTypeResponse])

  /**
   * Creates a Storage Box Snapshot. 
   * 
   * Expected answers:
   *   code 201 : CreateSnapshotResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param createSnapshotRequest 
   */
  def createSnapshot(id: Long, createSnapshotRequest: CreateSnapshotRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], CreateSnapshotResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/snapshots"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(createSnapshotRequest))
      .response(asJson[CreateSnapshotResponse])

  /**
   * Creates a Storage Box. 
   * 
   * Expected answers:
   *   code 201 : CreateStorageBoxResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param createStorageBoxRequest 
   */
  def createStorageBox(createStorageBoxRequest: CreateStorageBoxRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], CreateStorageBoxResponse]] =
    val requestURL =
      uri"$baseUrl/storage_boxes"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(createStorageBoxRequest))
      .response(asJson[CreateStorageBoxResponse])

  /**
   * Creates a Storage Box Subaccount.  A Storage Box Subaccount will use a separate home directory. 
   * 
   * Expected answers:
   *   code 201 : CreateSubaccountResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param createSubaccountRequest 
   */
  def createSubaccount(id: Long, createSubaccountRequest: CreateSubaccountRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], CreateSubaccountResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/subaccounts"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(createSubaccountRequest))
      .response(asJson[CreateSubaccountResponse])

  /**
   * Deletes a Storage Box Snapshot. 
   * 
   * Expected answers:
   *   code 201 : DeleteSnapshotResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param snapshotId ID of the Storage Box Snapshot.
   */
  def deleteSnapshot(id: Long, snapshotId: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], DeleteSnapshotResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val snapshotIdPathParam = PathSerializable.serialize("snapshot_id", snapshotId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/snapshots/${snapshotIdPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[DeleteSnapshotResponse])

  /**
   * Deletes a Storage Box. 
   * 
   * Expected answers:
   *   code 201 : DeleteStorageBoxResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   */
  def deleteStorageBox(id: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], DeleteStorageBoxResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[DeleteStorageBoxResponse])

  /**
   * Deletes a Storage Box Subaccount. 
   * 
   * Expected answers:
   *   code 201 : DeleteSubaccountResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param subaccountId ID of the Storage Box Subaccount.
   */
  def deleteSubaccount(id: Long, subaccountId: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], DeleteSubaccountResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val subaccountIdPathParam = PathSerializable.serialize("subaccount_id", subaccountId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/subaccounts/${subaccountIdPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[DeleteSubaccountResponse])

  /**
   * Disables the active Snapshot Plan of a Storage Box.  Existing Storage Box Snapshots created by the Snapshot Plan will not be delete, they must be removed manually. 
   * 
   * Expected answers:
   *   code 201 : DisableSnapshotPlanResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   */
  def disableSnapshotPlan(id: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], DisableSnapshotPlanResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/actions/disable_snapshot_plan"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[DisableSnapshotPlanResponse])

  /**
   * Enables a Snapshot Plan for a Storage Box.  Once enabled, a Snapshot Plan will create Snapshots at predefined intervals. There can only ever be one Snapshot Plan. The existing Snapshot Plan will be deleted before a new one is set up.  Automatic Snapshots are retained until explicitly deleted by the user or the maximum snapshot count for the plan (\"max_snapshots\") is exceeded.  You can choose the specific time (UTC timezone), day of the week, and day of the month. The time-related options are cron like. Some typical use cases include:  | Interval                                   | Request body                                                  | | ------------------------------------------ | ------------------------------------------------------------- | | Every day at 3 o'clock                     | `{\"max_snapshots\":10,\"minute\":0,\"hour\":3}`                    | | Every Friday at 3 o'clock                  | `{\"max_snapshots\":10,\"minute\":0,\"hour\":3,\"day_of_week\": 5}`   | | On the first of every month at half past 6 | `{\"max_snapshots\":10,\"minute\":30,\"hour\":6,\"day_of_month\": 1}` | 
   * 
   * Expected answers:
   *   code 201 : EnableSnapshotPlanResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param enableSnapshotPlanRequest 
   */
  def enableSnapshotPlan(id: Long, enableSnapshotPlanRequest: EnableSnapshotPlanRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], EnableSnapshotPlanResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/actions/enable_snapshot_plan"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(enableSnapshotPlanRequest))
      .response(asJson[EnableSnapshotPlanResponse])

  /**
   * Returns a specific Action object for a Storage Box. 
   * 
   * Expected answers:
   *   code 200 : GetActionResponse (The `action` key in the reply has this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param actionId ID of the Action.
   */
  def getActionForStorageBox(id: Long, actionId: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], GetActionResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val actionIdPathParam = PathSerializable.serialize("action_id", actionId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/actions/${actionIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /**
   * Returns a specific Storage Box Snapshot. 
   * 
   * Expected answers:
   *   code 200 : GetSnapshotResponse (The `snapshot` key in the reply contains a Snapshot object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param snapshotId ID of the Storage Box Snapshot.
   */
  def getSnapshot(id: Long, snapshotId: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], GetSnapshotResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val snapshotIdPathParam = PathSerializable.serialize("snapshot_id", snapshotId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/snapshots/${snapshotIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetSnapshotResponse])

  /**
   * Returns a specific Storage Box. 
   * 
   * Expected answers:
   *   code 200 : GetStorageBoxResponse (The `storage_box` key in the reply contains a Storage Box object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   */
  def getStorageBox(id: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], GetStorageBoxResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetStorageBoxResponse])

  /**
   * Returns a specific Action object. 
   * 
   * Expected answers:
   *   code 200 : GetActionResponse (The `action` key in the reply has this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Action.
   */
  def getStorageBoxAction(id: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], GetActionResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/actions/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /**
   * Returns a specific Storage Box Subaccount. 
   * 
   * Expected answers:
   *   code 200 : GetSubaccountResponse (The `subaccount` key in the reply contains a Subaccount object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param subaccountId ID of the Storage Box Subaccount.
   */
  def getSubaccount(id: Long, subaccountId: Long)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], GetSubaccountResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val subaccountIdPathParam = PathSerializable.serialize("subaccount_id", subaccountId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/subaccounts/${subaccountIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetSubaccountResponse])

  /**
   * List all Actions related to a specific Storage Box. 
   * 
   * Expected answers:
   *   code 200 : ListActionsResponse (The `actions` key contains a list of Actions.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param sort Sort actions by field and direction. Can be used multiple times. For more information, see \"Sorting\". 
   * @param status Filter the actions by status. Can be used multiple times. The response will only contain actions matching the specified statuses. 
   * @param page Page number to return. For more information, see \"Pagination\".
   * @param perPage Maximum number of entries returned per page. For more information, see \"Pagination\".
   */
  def listActionsForStorageBox(id: Long, sort: Seq[String], status: Seq[String], page: Option[Long] = scala.None, perPage: Option[Long] = scala.None)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ListActionsResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/actions"
        .addParams(FormSerializable.serialize("sort", sort, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("status", status, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("page", page, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("per_page", perPage, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /**
   * Returns a list of (sub)folders in a Storage Box.  The folder location is specified by the `path` query parameter. 
   * 
   * Expected answers:
   *   code 200 : ListFoldersOfStorageBoxResponse (The `folders` key lists the directories the Storage Box contains at the specified path.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param path Relative path for which the listing is to be made.
   */
  def listFoldersOfStorageBox(id: Long, path: Option[String] = scala.None)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ListFoldersOfStorageBoxResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/folders"
        .addParams(FormSerializable.serialize("path", path, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListFoldersOfStorageBoxResponse])

  /**
   * Returns a list of Storage Box Snapshot.  Both snapshots created manually and by the snapshot plan are returned. 
   * 
   * Expected answers:
   *   code 200 : ListSnapshotsResponse (The `snapshots` key contains a list of Snapshots.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param name Filter resources by their name. The response will only contain the resources matching exactly the specified name. 
   * @param labelSelector Filter resources by labels. The response will only contain resources matching the label selector. For more information, see \"Label Selector\". 
   * @param sort Sort resources by field and direction. Can be used multiple times. For more information, see \"Sorting\". 
   * @param isAutomatic Filter wether a Storage Box Snapshot is automatic. 
   */
  def listSnapshots(id: Long, name: Option[String] = scala.None, labelSelector: Option[String] = scala.None, sort: Seq[String], isAutomatic: Option[Boolean] = scala.None)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ListSnapshotsResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/snapshots"
        .addParams(FormSerializable.serialize("name", name, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("label_selector", labelSelector, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("sort", sort, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("is_automatic", isAutomatic, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListSnapshotsResponse])

  /**
   * Returns all Action objects. 
   * 
   * Expected answers:
   *   code 200 : ListActionsResponse (The `actions` key contains a list of Actions.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id Filter the actions by ID. Can be used multiple times. The response will only contain actions matching the specified IDs. 
   * @param sort Sort actions by field and direction. Can be used multiple times. For more information, see \"Sorting\". 
   * @param status Filter the actions by status. Can be used multiple times. The response will only contain actions matching the specified statuses. 
   * @param page Page number to return. For more information, see \"Pagination\".
   * @param perPage Maximum number of entries returned per page. For more information, see \"Pagination\".
   */
  def listStorageBoxActions(id: Seq[Long], sort: Seq[String], status: Seq[String], page: Option[Long] = scala.None, perPage: Option[Long] = scala.None)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ListActionsResponse]] =
    val requestURL =
      uri"$baseUrl/storage_boxes/actions"
        .addParams(FormSerializable.serialize("id", id, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("sort", sort, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("status", status, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("page", page, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("per_page", perPage, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /**
   * Returns a paginated list of Storage Boxes. 
   * 
   * Expected answers:
   *   code 200 : ListStorageBoxesResponse (The `storage_box` key in the reply contains a Storage Box object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param name Filter resources by their name. The response will only contain the resources matching exactly the specified name. 
   * @param labelSelector Filter resources by labels. The response will only contain resources matching the label selector. For more information, see \"Label Selector\". 
   * @param sort Sort resources by field and direction. Can be used multiple times. For more information, see \"Sorting\". 
   * @param page Page number to return. For more information, see \"Pagination\".
   * @param perPage Maximum number of entries returned per page. For more information, see \"Pagination\".
   */
  def listStorageBoxes(name: Option[String] = scala.None, labelSelector: Option[String] = scala.None, sort: Seq[String], page: Option[Long] = scala.None, perPage: Option[Long] = scala.None)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ListStorageBoxesResponse]] =
    val requestURL =
      uri"$baseUrl/storage_boxes"
        .addParams(FormSerializable.serialize("name", name, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("label_selector", labelSelector, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("sort", sort, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("page", page, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("per_page", perPage, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListStorageBoxesResponse])

  /**
   * Returns a list of Storage Box Subaccount. 
   * 
   * Expected answers:
   *   code 200 : ListSubaccountsResponse (The `subaccounts` key contains a list of Subaccounts.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param labelSelector Filter resources by labels. The response will only contain resources matching the label selector. For more information, see \"Label Selector\". 
   * @param sort Sort resources by field and direction. Can be used multiple times. For more information, see \"Sorting\". 
   * @param username Filter Storage Box Subaccounts by username. The response will only contain the resources matching exactly the specified username. 
   */
  def listSubaccounts(id: Long, labelSelector: Option[String] = scala.None, sort: Seq[String], username: Option[String] = scala.None)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ListSubaccountsResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/subaccounts"
        .addParams(FormSerializable.serialize("label_selector", labelSelector, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("sort", sort, FormStyleFormat.FORM, true): _*)
        .addParams(FormSerializable.serialize("username", username, FormStyleFormat.FORM, true): _*)

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListSubaccountsResponse])

  /**
   * Updates a Storage Box Snapshot. 
   * 
   * Expected answers:
   *   code 200 : ReplaceSnapshotResponse (The `snapshot` key contains the updated Snapshot.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param snapshotId ID of the Storage Box Snapshot.
   * @param replaceSnapshotRequest 
   */
  def replaceSnapshot(id: Long, snapshotId: Long, replaceSnapshotRequest: ReplaceSnapshotRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ReplaceSnapshotResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val snapshotIdPathParam = PathSerializable.serialize("snapshot_id", snapshotId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/snapshots/${snapshotIdPathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replaceSnapshotRequest))
      .response(asJson[ReplaceSnapshotResponse])

  /**
   * Updates a Storage Box. 
   * 
   * Expected answers:
   *   code 200 : ReplaceStorageBoxResponse (The `storage_box` key in the reply contains the updated Storage Box object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param replaceStorageBoxRequest 
   */
  def replaceStorageBox(id: Long, replaceStorageBoxRequest: ReplaceStorageBoxRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ReplaceStorageBoxResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replaceStorageBoxRequest))
      .response(asJson[ReplaceStorageBoxResponse])

  /**
   * Updates a Storage Box Subaccount. 
   * 
   * Expected answers:
   *   code 200 : ReplaceSubaccountResponse (The `subaccount` key contains the updated Subaccount.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param subaccountId ID of the Storage Box Subaccount.
   * @param replaceSubaccountRequest 
   */
  def replaceSubaccount(id: Long, subaccountId: Long, replaceSubaccountRequest: ReplaceSubaccountRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ReplaceSubaccountResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val subaccountIdPathParam = PathSerializable.serialize("subaccount_id", subaccountId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/subaccounts/${subaccountIdPathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replaceSubaccountRequest))
      .response(asJson[ReplaceSubaccountResponse])

  /**
   * Reset the password of a Storage Box. 
   * 
   * Expected answers:
   *   code 201 : ResetPasswordResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param resetPasswordRequest 
   */
  def resetStorageBoxPassword(id: Long, resetPasswordRequest: ResetPasswordRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ResetPasswordResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/actions/reset_password"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(resetPasswordRequest))
      .response(asJson[ResetPasswordResponse])

  /**
   * Reset the password of a Storage Box Subaccount. 
   * 
   * Expected answers:
   *   code 201 : ResetPasswordResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param subaccountId ID of the Storage Box Subaccount.
   * @param resetPasswordRequest 
   */
  def resetStorageBoxSubaccountPassword(id: Long, subaccountId: Long, resetPasswordRequest: ResetPasswordRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], ResetPasswordResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val subaccountIdPathParam = PathSerializable.serialize("subaccount_id", subaccountId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/subaccounts/${subaccountIdPathParam}/actions/reset_subaccount_password"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(resetPasswordRequest))
      .response(asJson[ResetPasswordResponse])

  /**
   * Rolls back a Storage Box to the given Storage Box Snapshot.  This will remove all newer Storage Box Snapshot and irrevocably delete all data that was since written to the Storage Box. 
   * 
   * Expected answers:
   *   code 201 : RollbackSnapshotResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param rollbackSnapshotRequest 
   */
  def rollbackSnapshot(id: Long, rollbackSnapshotRequest: RollbackSnapshotRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], RollbackSnapshotResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/actions/rollback_snapshot"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(rollbackSnapshotRequest))
      .response(asJson[RollbackSnapshotResponse])

  /**
   * Update access settings of a primary Storage Box account.  This endpoints supports partial updates. Omitted optional parameters do not result in any changes to the respective properties. 
   * 
   * Expected answers:
   *   code 201 : UpdateAccessSettingsResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param updateAccessSettingsRequest 
   */
  def updateStorageBoxAccessSettings(id: Long, updateAccessSettingsRequest: UpdateAccessSettingsRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], UpdateAccessSettingsResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/actions/update_access_settings"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(updateAccessSettingsRequest))
      .response(asJson[UpdateAccessSettingsResponse])

  /**
   * Updates the access settings of a Storage Box Subaccount.  This endpoints supports partial updates. Omitted optional parameters do not result in any changes to the respective properties. 
   * 
   * Expected answers:
   *   code 201 : UpdateAccessSettingsResponse (The `action` key in the reply contains an Action object with this structure.)
   * 
   * Available security schemes:
   *   APIToken (http)
   * 
   * @param id ID of the Storage Box.
   * @param subaccountId ID of the Storage Box Subaccount.
   * @param updateAccessSettingsRequest 
   */
  def updateStorageBoxSubaccountAccessSettings(id: Long, subaccountId: Long, updateAccessSettingsRequest: UpdateAccessSettingsRequest)(using Auth <:< hcloud.Authorization.BearerToken): sttp.client4.Request[Either[ResponseException[String], UpdateAccessSettingsResponse]] =
    val idPathParam = PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val subaccountIdPathParam = PathSerializable.serialize("subaccount_id", subaccountId, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/storage_boxes/${idPathParam}/subaccounts/${subaccountIdPathParam}/actions/update_access_settings"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(updateAccessSettingsRequest))
      .response(asJson[UpdateAccessSettingsResponse])

end StorageBoxes