/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.api

import hcloud.models.AttachVolumeToServerRequest
import hcloud.models.AttachVolumeToServerResponse
import hcloud.models.ChangeVolumeProtectionRequest
import hcloud.models.ChangeVolumeProtectionResponse
import hcloud.models.CreateVolumeRequest
import hcloud.models.CreateVolumeResponse
import hcloud.models.DetachVolumeResponse
import hcloud.models.GetActionResponse
import hcloud.models.GetVolumeResponse
import hcloud.models.ListActionsResponse
import hcloud.models.ListVolumesResponse
import hcloud.models.ReplaceVolumeRequest
import hcloud.models.ReplaceVolumeResponse
import hcloud.models.ResizeVolumeRequest
import hcloud.models.ResizeVolumeResponse
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object Volumes:
  def apply(
      baseUrl: String = "https://api.hetzner.cloud/v1"
  ): Volumes[hcloud.Authorization.NoAuthorization.type] =
    Volumes(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): Volumes[hcloud.Authorization.BasicAuth] =
    Volumes(baseUrl, hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): Volumes[hcloud.Authorization.ApiKey] =
    Volumes(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): Volumes[hcloud.Authorization.BearerToken] =
    Volumes(baseUrl, hcloud.Authorization.BearerToken(token))

case class Volumes[Auth <: hcloud.Authorization] private (
    baseUrl: String,
    authConfig: hcloud.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): Volumes[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): Volumes[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: Volumes[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): Volumes[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /** Attaches a Volume to a Server. Works only if the Server is in the same
    * Location as the Volume.
    *
    * Expected answers: code 201 : AttachVolumeToServerResponse (The `action`
    * key contains the `attach_volume` Action.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Volume.
    * @param attachVolumeToServerRequest
    */
  def attachVolumeToServer(
      id: Long,
      attachVolumeToServerRequest: AttachVolumeToServerRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], AttachVolumeToServerResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/volumes/${idPathParam}/actions/attach"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(attachVolumeToServerRequest))
      .response(asJson[AttachVolumeToServerResponse])

  /** Changes the protection configuration of a Volume.
    *
    * Expected answers: code 201 : ChangeVolumeProtectionResponse (The `action`
    * key contains the `change_protection` Action.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Volume.
    * @param changeVolumeProtectionRequest
    */
  def changeVolumeProtection(
      id: Long,
      changeVolumeProtectionRequest: ChangeVolumeProtectionRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ChangeVolumeProtectionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/volumes/${idPathParam}/actions/change_protection"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeVolumeProtectionRequest))
      .response(asJson[ChangeVolumeProtectionResponse])

  /** Creates a new Volume attached to a Server. If you want to create a Volume
    * that is not attached to a Server, you need to provide the `location` key
    * instead of `server`. This can be either the ID or the name of the Location
    * this Volume will be created in. Note that a Volume can be attached to a
    * Server only in the same Location as the Volume itself. Specifying the
    * Server during Volume creation will automatically attach the Volume to that
    * Server after it has been initialized. In that case, the `next_actions` key
    * in the response is an array which contains a single `attach_volume`
    * action. The minimum Volume size is 10GB and the maximum size is 10TB
    * (10240GB). A volume’s name can consist of alphanumeric characters, dashes,
    * underscores, and dots, but has to start and end with an alphanumeric
    * character. The total length is limited to 64 characters. Volume names must
    * be unique per Project. #### Call specific error codes | Code | Description | |-------------------------------------|-----------------------------------------------------| |
    * `no_space_left_in_location` | There is no volume space left in the given
    * location |
    *
    * Expected answers: code 201 : CreateVolumeResponse (The `volume` key
    * contains the Volume that was just created. The `action` key contains the
    * Action tracking Volume creation. )
    *
    * Available security schemes: APIToken (http)
    *
    * @param createVolumeRequest
    */
  def createVolume(createVolumeRequest: CreateVolumeRequest)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], CreateVolumeResponse]
  ] =
    val requestURL =
      uri"$baseUrl/volumes"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(createVolumeRequest))
      .response(asJson[CreateVolumeResponse])

  /** Deletes a volume. All Volume data is irreversibly destroyed. The Volume
    * must not be attached to a Server and it must not have delete protection
    * enabled.
    *
    * Expected answers: code 204 : (Volume deleted.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Volume.
    */
  def deleteVolume(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], Unit]] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/volumes/${idPathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(_ => Right(()))
        )
      )

  /** Detaches a Volume from the Server it’s attached to. You may attach it to a
    * Server again at a later time.
    *
    * Expected answers: code 201 : DetachVolumeResponse (The `action` key
    * contains the `detach_volume` Action.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Volume.
    */
  def detachVolume(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], DetachVolumeResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/volumes/${idPathParam}/actions/detach"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[DetachVolumeResponse])

  /** Returns a specific Action for a Volume.
    *
    * Expected answers: code 200 : GetActionResponse (The `action` key contains
    * the Volume Action.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Volume.
    * @param actionId
    *   ID of the Action.
    */
  def getActionForVolume(id: Long, actionId: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetActionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val actionIdPathParam = PathSerializable.serialize(
      "action_id",
      actionId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/volumes/${idPathParam}/actions/${actionIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /** Gets a specific Volume object.
    *
    * Expected answers: code 200 : GetVolumeResponse (The `volume` key contains
    * the volume.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Volume.
    */
  def getVolume(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetVolumeResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/volumes/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetVolumeResponse])

  /** Returns a specific Action object.
    *
    * Expected answers: code 200 : GetActionResponse (The `action` key in the
    * reply has this structure.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Action.
    */
  def getVolumeAction(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetActionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/volumes/actions/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /** Returns all Action objects for a Volume. You can `sort` the results by
    * using the sort URI parameter, and filter them with the `status` parameter.
    *
    * Expected answers: code 200 : ListActionsResponse (The `actions` key
    * contains a list of Actions.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Volume.
    * @param sort
    *   Sort actions by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param status
    *   Filter the actions by status. Can be used multiple times. The response
    *   will only contain actions matching the specified statuses.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listActionsForVolume(
      id: Long,
      sort: Seq[String],
      status: Seq[String],
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListActionsResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/volumes/${idPathParam}/actions"
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /** Returns all Action objects. You can `sort` the results by using the sort
    * URI parameter, and filter them with the `status` and `id` parameter.
    *
    * Expected answers: code 200 : ListActionsResponse (The `actions` key
    * contains a list of Actions.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   Filter the actions by ID. Can be used multiple times. The response will
    *   only contain actions matching the specified IDs.
    * @param sort
    *   Sort actions by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param status
    *   Filter the actions by status. Can be used multiple times. The response
    *   will only contain actions matching the specified statuses.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listVolumeActions(
      id: Seq[Long],
      sort: Seq[String],
      status: Seq[String],
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListActionsResponse]
  ] =
    val requestURL =
      uri"$baseUrl/volumes/actions"
        .addParams(
          FormSerializable.serialize("id", id, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /** Gets all existing Volumes that you have available.
    *
    * Expected answers: code 200 : ListVolumesResponse (The `volumes` key
    * contains a list of volumes.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param status
    *   Filter resources by status. Can be used multiple times. The response
    *   will only contain the resources with the specified status.
    * @param sort
    *   Sort resources by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param name
    *   Filter resources by their name. The response will only contain the
    *   resources matching exactly the specified name.
    * @param labelSelector
    *   Filter resources by labels. The response will only contain resources
    *   matching the label selector. For more information, see \"Label
    *   Selector\".
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listVolumes(
      status: Seq[String],
      sort: Seq[String],
      name: Option[String] = scala.None,
      labelSelector: Option[String] = scala.None,
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListVolumesResponse]
  ] =
    val requestURL =
      uri"$baseUrl/volumes"
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("name", name, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "label_selector",
            labelSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListVolumesResponse])

  /** Updates the Volume properties.
    *
    * Expected answers: code 200 : ReplaceVolumeResponse (The `volume` key
    * contains the updated volume.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Volume.
    * @param replaceVolumeRequest
    */
  def replaceVolume(id: Long, replaceVolumeRequest: ReplaceVolumeRequest)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ReplaceVolumeResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/volumes/${idPathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replaceVolumeRequest))
      .response(asJson[ReplaceVolumeResponse])

  /** Changes the size of a Volume. Note that downsizing a Volume is not
    * possible.
    *
    * Expected answers: code 201 : ResizeVolumeResponse (The `action` key
    * contains the `resize_volume` Action.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Volume.
    * @param resizeVolumeRequest
    */
  def resizeVolume(id: Long, resizeVolumeRequest: ResizeVolumeRequest)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ResizeVolumeResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/volumes/${idPathParam}/actions/resize"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(resizeVolumeRequest))
      .response(asJson[ResizeVolumeResponse])

end Volumes
