/** Hetzner Cloud API Copied from the official API documentation for the Public
  * Hetzner Cloud.
  *
  * The version of the OpenAPI document: f6511ca-dirty
  *
  * NOTE: This class is auto generated by OpenAPI Generator
  * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
  * the class manually.
  */
package hcloud.api

import hcloud.models.AddRecordsToRrsetRequest
import hcloud.models.AddRecordsToRrsetResponse
import hcloud.models.ChangeRrsetsProtectionRequest
import hcloud.models.ChangeRrsetsProtectionResponse
import hcloud.models.ChangeRrsetsTtlRequest
import hcloud.models.ChangeRrsetsTtlResponse
import hcloud.models.ChangeZonesDefaultTtlRequest
import hcloud.models.ChangeZonesDefaultTtlResponse
import hcloud.models.ChangeZonesPrimaryNameserversRequest
import hcloud.models.ChangeZonesPrimaryNameserversResponse
import hcloud.models.ChangeZonesProtectionRequest
import hcloud.models.ChangeZonesProtectionResponse
import hcloud.models.CreateRrsetResponse
import hcloud.models.CreateZoneRequest
import hcloud.models.CreateZoneResponse
import hcloud.models.DeleteRrsetResponse
import hcloud.models.DeleteZoneResponse
import hcloud.models.ExportZoneFileResponse
import hcloud.models.GetActionResponse
import hcloud.models.GetRrsetResponse
import hcloud.models.GetZoneResponse
import hcloud.models.ImportZoneFileRequest
import hcloud.models.ImportZoneFileResponse
import hcloud.models.ListActionsResponse
import hcloud.models.ListRrsetsResponse
import hcloud.models.ListZonesResponse
import hcloud.models.RemoveRecordsFromRrsetRequest
import hcloud.models.RemoveRecordsFromRrsetResponse
import hcloud.models.ReplaceRrsetRequest
import hcloud.models.ReplaceRrsetResponse
import hcloud.models.ReplaceZoneRequest
import hcloud.models.ReplaceZoneResponse
import hcloud.models.ResourceRecordSetToCreate
import hcloud.models.SetRecordsOfRrsetRequest
import hcloud.models.SetRecordsOfRrsetResponse
import hcloud.models.UpdateRecordsOfRrsetRequest
import hcloud.models.UpdateRecordsOfRrsetResponse
import hcloud.JsonSupport.{*, given}
import hcloud.FormSerializable
import hcloud.FormStyleFormat
import hcloud.HeaderSerializable
import hcloud.ApiKeyLocation
import hcloud.PathStyleFormat
import hcloud.PathSerializable
import hcloud.CookieSerializable
import hcloud.Helpers.*
import sttp.client4.jsoniter.*
import sttp.client4.*
import sttp.model.Method

object Zones:
  def apply(
      baseUrl: String = "https://api.hetzner.cloud/v1"
  ): Zones[hcloud.Authorization.NoAuthorization.type] =
    Zones(baseUrl, hcloud.Authorization.NoAuthorization)
  def withBasicAuth(
      baseUrl: String,
      username: String,
      password: String
  ): Zones[hcloud.Authorization.BasicAuth] =
    Zones(baseUrl, hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(
      baseUrl: String,
      apiKey: String
  ): Zones[hcloud.Authorization.ApiKey] =
    Zones(baseUrl, hcloud.Authorization.ApiKey(apiKey))

  def withBearerTokenAuth(
      baseUrl: String,
      token: String
  ): Zones[hcloud.Authorization.BearerToken] =
    Zones(baseUrl, hcloud.Authorization.BearerToken(token))

case class Zones[Auth <: hcloud.Authorization] private (
    baseUrl: String,
    authConfig: hcloud.Authorization
):
  def withBasicAuth(
      username: String,
      password: String
  ): Zones[hcloud.Authorization.BasicAuth] =
    copy(authConfig = hcloud.Authorization.BasicAuth(username, password))

  def withApiKeyAuth(apiKey: String): Zones[hcloud.Authorization.ApiKey] =
    copy(authConfig = hcloud.Authorization.ApiKey(apiKey))

  def withNoAuth: Zones[hcloud.Authorization.NoAuthorization.type] =
    copy(authConfig = hcloud.Authorization.NoAuthorization)

  def withBearerTokenAuth(
      token: String
  ): Zones[hcloud.Authorization.BearerToken] =
    copy(authConfig = hcloud.Authorization.BearerToken(token))

  /** Adds resource records (RRs) to an RRSet in the Zone. For convenience, the
    * RRSet will be automatically created if it doesn't exist. Otherwise, the
    * new records are appended to the existing RRSet. Only applicable for Zones
    * in primary mode. #### Call specific error codes | Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 201 : AddRecordsToRrsetResponse (Request
    * succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param rrName
    * @param rrType
    * @param addRecordsToRrsetRequest
    */
  def addRecordsToRrset(
      idOrName: String,
      rrName: String,
      rrType: String,
      addRecordsToRrsetRequest: AddRecordsToRrsetRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], AddRecordsToRrsetResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrNamePathParam = PathSerializable.serialize(
      "rr_name",
      rrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrTypePathParam = PathSerializable.serialize(
      "rr_type",
      rrType,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/rrsets/${rrNamePathParam}/${rrTypePathParam}/actions/add_records"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(addRecordsToRrsetRequest))
      .response(asJson[AddRecordsToRrsetResponse])

  /** Changes the protection of an RRSet in the Zone. Only applicable for Zones
    * in primary mode. #### Call specific error codes | Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 201 : ChangeRrsetsProtectionResponse (Request
    * succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param rrName
    * @param rrType
    * @param changeRrsetsProtectionRequest
    */
  def changeRrsetsProtection(
      idOrName: String,
      rrName: String,
      rrType: String,
      changeRrsetsProtectionRequest: ChangeRrsetsProtectionRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ChangeRrsetsProtectionResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrNamePathParam = PathSerializable.serialize(
      "rr_name",
      rrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrTypePathParam = PathSerializable.serialize(
      "rr_type",
      rrType,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/rrsets/${rrNamePathParam}/${rrTypePathParam}/actions/change_protection"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeRrsetsProtectionRequest))
      .response(asJson[ChangeRrsetsProtectionResponse])

  /** Changes the Time To Live (TTL) of an RRSet in the Zone. Only applicable
    * for Zones in primary mode. #### Call specific error codes | Code |
    * Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 201 : ChangeRrsetsTtlResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param rrName
    * @param rrType
    * @param changeRrsetsTtlRequest
    */
  def changeRrsetsTtl(
      idOrName: String,
      rrName: String,
      rrType: String,
      changeRrsetsTtlRequest: ChangeRrsetsTtlRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ChangeRrsetsTtlResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrNamePathParam = PathSerializable.serialize(
      "rr_name",
      rrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrTypePathParam = PathSerializable.serialize(
      "rr_type",
      rrType,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/rrsets/${rrNamePathParam}/${rrTypePathParam}/actions/change_ttl"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeRrsetsTtlRequest))
      .response(asJson[ChangeRrsetsTtlResponse])

  /** Changes the default Time To Live (TTL) of a Zone. This TTL is used for
    * RRSets that do not explicitly define a TTL. Only applicable for Zones in
    * primary mode. #### Call specific error codes | Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 201 : ChangeZonesDefaultTtlResponse (Request
    * succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param changeZonesDefaultTtlRequest
    */
  def changeZonesDefaultTtl(
      idOrName: String,
      changeZonesDefaultTtlRequest: ChangeZonesDefaultTtlRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ChangeZonesDefaultTtlResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/actions/change_ttl"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeZonesDefaultTtlRequest))
      .response(asJson[ChangeZonesDefaultTtlResponse])

  /** Overwrites the primary nameservers of a Zone. Only applicable for Zones in
    * secondary mode. #### Call specific error codes | Code | Description | |-----------------------|------------------------------------| |
    * `incorrect_zone_mode` | The zone is not in secondary mode. |
    *
    * Expected answers: code 201 : ChangeZonesPrimaryNameserversResponse
    * (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param changeZonesPrimaryNameserversRequest
    */
  def changeZonesPrimaryNameservers(
      idOrName: String,
      changeZonesPrimaryNameserversRequest: ChangeZonesPrimaryNameserversRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ChangeZonesPrimaryNameserversResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/actions/change_primary_nameservers"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeZonesPrimaryNameserversRequest))
      .response(asJson[ChangeZonesPrimaryNameserversResponse])

  /** Changes the protection configuration of a Zone.
    *
    * Expected answers: code 201 : ChangeZonesProtectionResponse (Request
    * succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param changeZonesProtectionRequest
    */
  def changeZonesProtection(
      idOrName: String,
      changeZonesProtectionRequest: ChangeZonesProtectionRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ChangeZonesProtectionResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/actions/change_protection"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(changeZonesProtectionRequest))
      .response(asJson[ChangeZonesProtectionResponse])

  /** Create an RRSet in the Zone. Only applicable for Zones in primary mode. |
    * Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 201 : CreateRrsetResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param body
    */
  def createRrset(idOrName: String, body: ResourceRecordSetToCreate)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], CreateRrsetResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/rrsets"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(body))
      .response(asJson[CreateRrsetResponse])

  /** Creates a Zone. A default `SOA` and three `NS` resource records with the
    * assigned Hetzner nameservers are created automatically.
    *
    * Expected answers: code 201 : CreateZoneResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param createZoneRequest
    */
  def createZone(createZoneRequest: CreateZoneRequest)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], CreateZoneResponse]
  ] =
    val requestURL =
      uri"$baseUrl/zones"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(createZoneRequest))
      .response(asJson[CreateZoneResponse])

  /** Deletes an RRSet from the Zone. Only applicable for Zones in primary mode. |
    * Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 201 : DeleteRrsetResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param rrName
    * @param rrType
    */
  def deleteRrset(idOrName: String, rrName: String, rrType: String)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], DeleteRrsetResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrNamePathParam = PathSerializable.serialize(
      "rr_name",
      rrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrTypePathParam = PathSerializable.serialize(
      "rr_type",
      rrType,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/rrsets/${rrNamePathParam}/${rrTypePathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[DeleteRrsetResponse])

  /** Deletes a Zone.
    *
    * Expected answers: code 200 : DeleteZoneResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    */
  def deleteZone(idOrName: String)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], DeleteZoneResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}"

    basicRequest
      .method(Method.DELETE, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[DeleteZoneResponse])

  /** Returns a generated Zone file in BIND (RFC
    * [1034](https://datatracker.ietf.org/doc/html/rfc1034)/[1035](https://datatracker.ietf.org/doc/html/rfc1035))
    * format. Only applicable for Zones in primary mode. #### Call specific
    * error codes | Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 200 : ExportZoneFileResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    */
  def exportZoneFile(idOrName: String)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ExportZoneFileResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/zonefile"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ExportZoneFileResponse])

  /** Returns a specific Action for a Zone.
    *
    * Expected answers: code 200 : GetActionResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param actionId
    *   ID of the Action.
    */
  def getActionForZone(idOrName: String, actionId: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetActionResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val actionIdPathParam = PathSerializable.serialize(
      "action_id",
      actionId,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/actions/${actionIdPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /** Returns a single RRSet from the Zone. Only applicable for Zones in primary
    * mode. #### Call specific error codes | Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 200 : GetRrsetResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param rrName
    * @param rrType
    */
  def getRrset(idOrName: String, rrName: String, rrType: String)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], GetRrsetResponse]] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrNamePathParam = PathSerializable.serialize(
      "rr_name",
      rrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrTypePathParam = PathSerializable.serialize(
      "rr_type",
      rrType,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/rrsets/${rrNamePathParam}/${rrTypePathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetRrsetResponse])

  /** Returns a single Zone.
    *
    * Expected answers: code 200 : GetZoneResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    */
  def getZone(idOrName: String)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[Either[ResponseException[String], GetZoneResponse]] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetZoneResponse])

  /** Returns a specific Action.
    *
    * Expected answers: code 200 : GetActionResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   ID of the Action.
    */
  def getZoneAction(id: Long)(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], GetActionResponse]
  ] =
    val idPathParam =
      PathSerializable.serialize("id", id, PathStyleFormat.SIMPLE, false)
    val requestURL =
      uri"$baseUrl/zones/actions/${idPathParam}"

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[GetActionResponse])

  /** Imports a zone file, replacing all resource record sets (RRSets). The
    * import will fail if existing RRSet are `change` protected. See Zone file
    * import for more details. Only applicable for Zones in primary mode. ####
    * Call specific error codes | Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 201 : ImportZoneFileResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param importZoneFileRequest
    */
  def importZoneFile(
      idOrName: String,
      importZoneFileRequest: ImportZoneFileRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ImportZoneFileResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/actions/import_zonefile"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(importZoneFileRequest))
      .response(asJson[ImportZoneFileResponse])

  /** Returns all Actions for a Zone. Use the provided URI parameters to modify
    * the result.
    *
    * Expected answers: code 200 : ListActionsResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param sort
    *   Sort actions by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param status
    *   Filter the actions by status. Can be used multiple times. The response
    *   will only contain actions matching the specified statuses.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listActionsForZone(
      idOrName: String,
      sort: Seq[String],
      status: Seq[String],
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListActionsResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/actions"
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /** Returns all RRSets in the Zone. Use the provided URI parameters to modify
    * the result. The maximum value for `per_page` on this endpoint is `100`
    * instead of `50`. Only applicable for Zones in primary mode. #### Call
    * specific error codes | Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 200 : ListRrsetsResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param name
    *   Filter resources by their name. The response will only contain the
    *   resources matching exactly the specified name.
    * @param `type`
    *   Filter resources by their type. Can be used multiple times. The response
    *   will only contain resources matching the specified types.
    * @param labelSelector
    *   Filter resources by labels. The response will only contain resources
    *   matching the label selector. For more information, see \"Label
    *   Selector\".
    * @param sort
    *   Sort resources by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listRrsets(
      idOrName: String,
      name: Option[String] = scala.None,
      `type`: Seq[String],
      labelSelector: Option[String] = scala.None,
      sort: Seq[String],
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListRrsetsResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/rrsets"
        .addParams(
          FormSerializable
            .serialize("name", name, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("type", `type`, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "label_selector",
            labelSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListRrsetsResponse])

  /** Returns all Zone Actions. Use the provided URI parameters to modify the
    * result.
    *
    * Expected answers: code 200 : ListActionsResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param id
    *   Filter the actions by ID. Can be used multiple times. The response will
    *   only contain actions matching the specified IDs.
    * @param sort
    *   Sort actions by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param status
    *   Filter the actions by status. Can be used multiple times. The response
    *   will only contain actions matching the specified statuses.
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listZoneActions(
      id: Seq[Long],
      sort: Seq[String],
      status: Seq[String],
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListActionsResponse]
  ] =
    val requestURL =
      uri"$baseUrl/zones/actions"
        .addParams(
          FormSerializable.serialize("id", id, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("status", status, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListActionsResponse])

  /** Returns all Zones. Use the provided URI parameters to modify the result.
    *
    * Expected answers: code 200 : ListZonesResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param name
    *   Filter resources by their name. The response will only contain the
    *   resources matching exactly the specified name.
    * @param mode
    *   Filter resources by their mode. The response will only contain the
    *   resources matching exactly the specified mode.
    * @param labelSelector
    *   Filter resources by labels. The response will only contain resources
    *   matching the label selector. For more information, see \"Label
    *   Selector\".
    * @param sort
    *   Sort resources by field and direction. Can be used multiple times. For
    *   more information, see \"Sorting\".
    * @param page
    *   Page number to return. For more information, see \"Pagination\".
    * @param perPage
    *   Maximum number of entries returned per page. For more information, see
    *   \"Pagination\".
    */
  def listZones(
      name: Option[String] = scala.None,
      mode: Option[String] = scala.None,
      labelSelector: Option[String] = scala.None,
      sort: Seq[String],
      page: Option[Long] = scala.None,
      perPage: Option[Long] = scala.None
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ListZonesResponse]
  ] =
    val requestURL =
      uri"$baseUrl/zones"
        .addParams(
          FormSerializable
            .serialize("name", name, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("mode", mode, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable.serialize(
            "label_selector",
            labelSelector,
            FormStyleFormat.FORM,
            true
          ): _*
        )
        .addParams(
          FormSerializable
            .serialize("sort", sort, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("page", page, FormStyleFormat.FORM, true): _*
        )
        .addParams(
          FormSerializable
            .serialize("per_page", perPage, FormStyleFormat.FORM, true): _*
        )

    basicRequest
      .method(Method.GET, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .response(asJson[ListZonesResponse])

  /** Removes resource records (RRs) from an existing RRSet in the Zone. For
    * convenience, the RRSet will be automatically deleted if it doesn't contain
    * any RRs afterwards. Only applicable for Zones in primary mode. #### Call
    * specific error codes | Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 201 : RemoveRecordsFromRrsetResponse (Request
    * succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param rrName
    * @param rrType
    * @param removeRecordsFromRrsetRequest
    */
  def removeRecordsFromRrset(
      idOrName: String,
      rrName: String,
      rrType: String,
      removeRecordsFromRrsetRequest: RemoveRecordsFromRrsetRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], RemoveRecordsFromRrsetResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrNamePathParam = PathSerializable.serialize(
      "rr_name",
      rrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrTypePathParam = PathSerializable.serialize(
      "rr_type",
      rrType,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/rrsets/${rrNamePathParam}/${rrTypePathParam}/actions/remove_records"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(removeRecordsFromRrsetRequest))
      .response(asJson[RemoveRecordsFromRrsetResponse])

  /** Updates an RRSet in the Zone. Only applicable for Zones in primary mode. |
    * Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 200 : ReplaceRrsetResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param rrName
    * @param rrType
    * @param replaceRrsetRequest
    */
  def replaceRrset(
      idOrName: String,
      rrName: String,
      rrType: String,
      replaceRrsetRequest: ReplaceRrsetRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ReplaceRrsetResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrNamePathParam = PathSerializable.serialize(
      "rr_name",
      rrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrTypePathParam = PathSerializable.serialize(
      "rr_type",
      rrType,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/rrsets/${rrNamePathParam}/${rrTypePathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replaceRrsetRequest))
      .response(asJson[ReplaceRrsetResponse])

  /** Updates a Zone. To modify resource record sets (RRSets), use the RRSet
    * Actions endpoints.
    *
    * Expected answers: code 200 : ReplaceZoneResponse (Request succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param replaceZoneRequest
    */
  def replaceZone(idOrName: String, replaceZoneRequest: ReplaceZoneRequest)(
      using Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], ReplaceZoneResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}"

    basicRequest
      .method(Method.PUT, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(replaceZoneRequest))
      .response(asJson[ReplaceZoneResponse])

  /** Overwrites the resource records (RRs) of an existing RRSet in the Zone.
    * Only applicable for Zones in primary mode. #### Call specific error codes |
    * Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 201 : SetRecordsOfRrsetResponse (Request
    * succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param rrName
    * @param rrType
    * @param setRecordsOfRrsetRequest
    */
  def setRecordsOfRrset(
      idOrName: String,
      rrName: String,
      rrType: String,
      setRecordsOfRrsetRequest: SetRecordsOfRrsetRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], SetRecordsOfRrsetResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrNamePathParam = PathSerializable.serialize(
      "rr_name",
      rrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrTypePathParam = PathSerializable.serialize(
      "rr_type",
      rrType,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/rrsets/${rrNamePathParam}/${rrTypePathParam}/actions/set_records"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(setRecordsOfRrsetRequest))
      .response(asJson[SetRecordsOfRrsetResponse])

  /** Updates resource records' (RRs) comments of an existing RRSet in the Zone.
    * Only applicable for Zones in primary mode. #### Call specific error codes |
    * Code | Description | |-----------------------|----------------------------------| |
    * `incorrect_zone_mode` | The zone is not in primary mode. |
    *
    * Expected answers: code 200 : UpdateRecordsOfRrsetResponse (Request
    * succeeded.)
    *
    * Available security schemes: APIToken (http)
    *
    * @param idOrName
    *   ID or Name of the Zone.
    * @param rrName
    * @param rrType
    * @param updateRecordsOfRrsetRequest
    */
  def updateRecordsOfRrset(
      idOrName: String,
      rrName: String,
      rrType: String,
      updateRecordsOfRrsetRequest: UpdateRecordsOfRrsetRequest
  )(using
      Auth <:< hcloud.Authorization.BearerToken
  ): sttp.client4.Request[
    Either[ResponseException[String], UpdateRecordsOfRrsetResponse]
  ] =
    val idOrNamePathParam = PathSerializable.serialize(
      "id_or_name",
      idOrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrNamePathParam = PathSerializable.serialize(
      "rr_name",
      rrName,
      PathStyleFormat.SIMPLE,
      false
    )
    val rrTypePathParam = PathSerializable.serialize(
      "rr_type",
      rrType,
      PathStyleFormat.SIMPLE,
      false
    )
    val requestURL =
      uri"$baseUrl/zones/${idOrNamePathParam}/rrsets/${rrNamePathParam}/${rrTypePathParam}/actions/update_records"

    basicRequest
      .method(Method.POST, requestURL)
      .contentType("application/json")
      .auth(authConfig)
      .body(asJson(updateRecordsOfRrsetRequest))
      .response(asJson[UpdateRecordsOfRrsetResponse])

end Zones
