package routes
import hcloud.models.StorageBox
import hcloud.api.StorageBoxes
import hcloud.models.ChangeHomeDirectoryRequest
import hcloud.models.ChangeHomeDirectoryResponse
import hcloud.models.ChangeProtectionRequest
import hcloud.models.ChangeProtectionResponse
import hcloud.models.ChangeTypeRequest
import hcloud.models.ChangeTypeResponse
import hcloud.models.CreateSnapshotRequest
import hcloud.models.CreateSnapshotResponse
import hcloud.models.CreateStorageBoxRequest
import hcloud.models.CreateStorageBoxResponse
import hcloud.models.CreateSubaccountRequest
import hcloud.models.CreateSubaccountResponse
import hcloud.models.DeleteSnapshotResponse
import hcloud.models.DeleteStorageBoxResponse
import hcloud.models.DeleteSubaccountResponse
import hcloud.models.DisableSnapshotPlanResponse
import hcloud.models.EnableSnapshotPlanRequest
import hcloud.models.EnableSnapshotPlanResponse
import hcloud.models.GetActionResponse
import hcloud.models.GetSnapshotResponse
import hcloud.models.GetStorageBoxResponse
import hcloud.models.GetSubaccountResponse
import hcloud.models.ListActionsResponse
import hcloud.models.ListFoldersOfStorageBoxResponse
import hcloud.models.ListSnapshotsResponse
import hcloud.models.ListStorageBoxesResponse
import hcloud.models.ListSubaccountsResponse
import hcloud.models.ReplaceSnapshotRequest
import hcloud.models.ReplaceSnapshotResponse
import hcloud.models.ReplaceStorageBoxRequest
import hcloud.models.ReplaceStorageBoxResponse
import hcloud.models.ReplaceSubaccountRequest
import hcloud.models.ReplaceSubaccountResponse
import hcloud.models.ResetPasswordRequest
import hcloud.models.ResetPasswordResponse
import hcloud.models.RollbackSnapshotRequest
import hcloud.models.RollbackSnapshotResponse
import hcloud.models.UpdateAccessSettingsRequest
import hcloud.models.UpdateAccessSettingsResponse
import hcloud.JsonSupport.{*, given}
import org.http4s.AuthedRoutes
import org.http4s.dsl.Http4sDsl
import cats.effect.kernel.Concurrent
import sttp.client4.Backend
import cats.syntax.flatMap.toFlatMapOps

abstract class StorageBoxeRoutes[F[*]: Concurrent](backend: Backend[F])
    extends Http4sDsl[F] {}
